version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - lll
    - staticcheck
    - unused
  settings:
    staticcheck:
      checks: ["all", "-SA1019", "-ST1003", "-ST1012"] # ignore deprecated, ignore poorly chosen identifier and ignore poorly chosen name for error variable
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/bucketeer-io/go-server-sdk
  exclusions:
    generated: lax
