// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/feature/command.proto

package feature

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command struct {
	Command              *any.Any `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetCommand() *any.Any {
	if m != nil {
		return m.Command
	}
	return nil
}

type CreateFeatureCommand struct {
	Id                       string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                     string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description              string                `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Variations               []*Variation          `protobuf:"bytes,4,rep,name=variations,proto3" json:"variations,omitempty"`
	Tags                     []string              `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	DefaultOnVariationIndex  *wrappers.Int32Value  `protobuf:"bytes,6,opt,name=default_on_variation_index,json=defaultOnVariationIndex,proto3" json:"default_on_variation_index,omitempty"`
	DefaultOffVariationIndex *wrappers.Int32Value  `protobuf:"bytes,7,opt,name=default_off_variation_index,json=defaultOffVariationIndex,proto3" json:"default_off_variation_index,omitempty"`
	VariationType            Feature_VariationType `protobuf:"varint,8,opt,name=variation_type,json=variationType,proto3,enum=bucketeer.feature.Feature_VariationType" json:"variation_type,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}              `json:"-"`
	XXX_unrecognized         []byte                `json:"-"`
	XXX_sizecache            int32                 `json:"-"`
}

func (m *CreateFeatureCommand) Reset()         { *m = CreateFeatureCommand{} }
func (m *CreateFeatureCommand) String() string { return proto.CompactTextString(m) }
func (*CreateFeatureCommand) ProtoMessage()    {}
func (*CreateFeatureCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{1}
}

func (m *CreateFeatureCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFeatureCommand.Unmarshal(m, b)
}
func (m *CreateFeatureCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFeatureCommand.Marshal(b, m, deterministic)
}
func (m *CreateFeatureCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFeatureCommand.Merge(m, src)
}
func (m *CreateFeatureCommand) XXX_Size() int {
	return xxx_messageInfo_CreateFeatureCommand.Size(m)
}
func (m *CreateFeatureCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFeatureCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFeatureCommand proto.InternalMessageInfo

func (m *CreateFeatureCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateFeatureCommand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateFeatureCommand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateFeatureCommand) GetVariations() []*Variation {
	if m != nil {
		return m.Variations
	}
	return nil
}

func (m *CreateFeatureCommand) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *CreateFeatureCommand) GetDefaultOnVariationIndex() *wrappers.Int32Value {
	if m != nil {
		return m.DefaultOnVariationIndex
	}
	return nil
}

func (m *CreateFeatureCommand) GetDefaultOffVariationIndex() *wrappers.Int32Value {
	if m != nil {
		return m.DefaultOffVariationIndex
	}
	return nil
}

func (m *CreateFeatureCommand) GetVariationType() Feature_VariationType {
	if m != nil {
		return m.VariationType
	}
	return Feature_STRING
}

type ArchiveFeatureCommand struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArchiveFeatureCommand) Reset()         { *m = ArchiveFeatureCommand{} }
func (m *ArchiveFeatureCommand) String() string { return proto.CompactTextString(m) }
func (*ArchiveFeatureCommand) ProtoMessage()    {}
func (*ArchiveFeatureCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{2}
}

func (m *ArchiveFeatureCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArchiveFeatureCommand.Unmarshal(m, b)
}
func (m *ArchiveFeatureCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArchiveFeatureCommand.Marshal(b, m, deterministic)
}
func (m *ArchiveFeatureCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArchiveFeatureCommand.Merge(m, src)
}
func (m *ArchiveFeatureCommand) XXX_Size() int {
	return xxx_messageInfo_ArchiveFeatureCommand.Size(m)
}
func (m *ArchiveFeatureCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ArchiveFeatureCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ArchiveFeatureCommand proto.InternalMessageInfo

type DeleteFeatureCommand struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFeatureCommand) Reset()         { *m = DeleteFeatureCommand{} }
func (m *DeleteFeatureCommand) String() string { return proto.CompactTextString(m) }
func (*DeleteFeatureCommand) ProtoMessage()    {}
func (*DeleteFeatureCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{3}
}

func (m *DeleteFeatureCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFeatureCommand.Unmarshal(m, b)
}
func (m *DeleteFeatureCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFeatureCommand.Marshal(b, m, deterministic)
}
func (m *DeleteFeatureCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFeatureCommand.Merge(m, src)
}
func (m *DeleteFeatureCommand) XXX_Size() int {
	return xxx_messageInfo_DeleteFeatureCommand.Size(m)
}
func (m *DeleteFeatureCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFeatureCommand.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFeatureCommand proto.InternalMessageInfo

type RenameFeatureCommand struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameFeatureCommand) Reset()         { *m = RenameFeatureCommand{} }
func (m *RenameFeatureCommand) String() string { return proto.CompactTextString(m) }
func (*RenameFeatureCommand) ProtoMessage()    {}
func (*RenameFeatureCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{4}
}

func (m *RenameFeatureCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameFeatureCommand.Unmarshal(m, b)
}
func (m *RenameFeatureCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameFeatureCommand.Marshal(b, m, deterministic)
}
func (m *RenameFeatureCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameFeatureCommand.Merge(m, src)
}
func (m *RenameFeatureCommand) XXX_Size() int {
	return xxx_messageInfo_RenameFeatureCommand.Size(m)
}
func (m *RenameFeatureCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameFeatureCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RenameFeatureCommand proto.InternalMessageInfo

func (m *RenameFeatureCommand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ChangeDescriptionCommand struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeDescriptionCommand) Reset()         { *m = ChangeDescriptionCommand{} }
func (m *ChangeDescriptionCommand) String() string { return proto.CompactTextString(m) }
func (*ChangeDescriptionCommand) ProtoMessage()    {}
func (*ChangeDescriptionCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{5}
}

func (m *ChangeDescriptionCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeDescriptionCommand.Unmarshal(m, b)
}
func (m *ChangeDescriptionCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeDescriptionCommand.Marshal(b, m, deterministic)
}
func (m *ChangeDescriptionCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeDescriptionCommand.Merge(m, src)
}
func (m *ChangeDescriptionCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeDescriptionCommand.Size(m)
}
func (m *ChangeDescriptionCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeDescriptionCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeDescriptionCommand proto.InternalMessageInfo

func (m *ChangeDescriptionCommand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ChangeBulkUploadSegmentUsersStatusCommand struct {
	Status               Segment_Status    `protobuf:"varint,1,opt,name=status,proto3,enum=bucketeer.feature.Segment_Status" json:"status,omitempty"`
	State                SegmentUser_State `protobuf:"varint,2,opt,name=state,proto3,enum=bucketeer.feature.SegmentUser_State" json:"state,omitempty"`
	Count                int64             `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChangeBulkUploadSegmentUsersStatusCommand) Reset() {
	*m = ChangeBulkUploadSegmentUsersStatusCommand{}
}
func (m *ChangeBulkUploadSegmentUsersStatusCommand) String() string {
	return proto.CompactTextString(m)
}
func (*ChangeBulkUploadSegmentUsersStatusCommand) ProtoMessage() {}
func (*ChangeBulkUploadSegmentUsersStatusCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{6}
}

func (m *ChangeBulkUploadSegmentUsersStatusCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeBulkUploadSegmentUsersStatusCommand.Unmarshal(m, b)
}
func (m *ChangeBulkUploadSegmentUsersStatusCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeBulkUploadSegmentUsersStatusCommand.Marshal(b, m, deterministic)
}
func (m *ChangeBulkUploadSegmentUsersStatusCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeBulkUploadSegmentUsersStatusCommand.Merge(m, src)
}
func (m *ChangeBulkUploadSegmentUsersStatusCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeBulkUploadSegmentUsersStatusCommand.Size(m)
}
func (m *ChangeBulkUploadSegmentUsersStatusCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeBulkUploadSegmentUsersStatusCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeBulkUploadSegmentUsersStatusCommand proto.InternalMessageInfo

func (m *ChangeBulkUploadSegmentUsersStatusCommand) GetStatus() Segment_Status {
	if m != nil {
		return m.Status
	}
	return Segment_INITIAL
}

func (m *ChangeBulkUploadSegmentUsersStatusCommand) GetState() SegmentUser_State {
	if m != nil {
		return m.State
	}
	return SegmentUser_INCLUDED
}

func (m *ChangeBulkUploadSegmentUsersStatusCommand) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type AddTagCommand struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagCommand) Reset()         { *m = AddTagCommand{} }
func (m *AddTagCommand) String() string { return proto.CompactTextString(m) }
func (*AddTagCommand) ProtoMessage()    {}
func (*AddTagCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{7}
}

func (m *AddTagCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagCommand.Unmarshal(m, b)
}
func (m *AddTagCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagCommand.Marshal(b, m, deterministic)
}
func (m *AddTagCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagCommand.Merge(m, src)
}
func (m *AddTagCommand) XXX_Size() int {
	return xxx_messageInfo_AddTagCommand.Size(m)
}
func (m *AddTagCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagCommand.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagCommand proto.InternalMessageInfo

func (m *AddTagCommand) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type RemoveTagCommand struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTagCommand) Reset()         { *m = RemoveTagCommand{} }
func (m *RemoveTagCommand) String() string { return proto.CompactTextString(m) }
func (*RemoveTagCommand) ProtoMessage()    {}
func (*RemoveTagCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{8}
}

func (m *RemoveTagCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTagCommand.Unmarshal(m, b)
}
func (m *RemoveTagCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTagCommand.Marshal(b, m, deterministic)
}
func (m *RemoveTagCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTagCommand.Merge(m, src)
}
func (m *RemoveTagCommand) XXX_Size() int {
	return xxx_messageInfo_RemoveTagCommand.Size(m)
}
func (m *RemoveTagCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTagCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTagCommand proto.InternalMessageInfo

func (m *RemoveTagCommand) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type EnableFeatureCommand struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableFeatureCommand) Reset()         { *m = EnableFeatureCommand{} }
func (m *EnableFeatureCommand) String() string { return proto.CompactTextString(m) }
func (*EnableFeatureCommand) ProtoMessage()    {}
func (*EnableFeatureCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{9}
}

func (m *EnableFeatureCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableFeatureCommand.Unmarshal(m, b)
}
func (m *EnableFeatureCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableFeatureCommand.Marshal(b, m, deterministic)
}
func (m *EnableFeatureCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableFeatureCommand.Merge(m, src)
}
func (m *EnableFeatureCommand) XXX_Size() int {
	return xxx_messageInfo_EnableFeatureCommand.Size(m)
}
func (m *EnableFeatureCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableFeatureCommand.DiscardUnknown(m)
}

var xxx_messageInfo_EnableFeatureCommand proto.InternalMessageInfo

type DisableFeatureCommand struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableFeatureCommand) Reset()         { *m = DisableFeatureCommand{} }
func (m *DisableFeatureCommand) String() string { return proto.CompactTextString(m) }
func (*DisableFeatureCommand) ProtoMessage()    {}
func (*DisableFeatureCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{10}
}

func (m *DisableFeatureCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableFeatureCommand.Unmarshal(m, b)
}
func (m *DisableFeatureCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableFeatureCommand.Marshal(b, m, deterministic)
}
func (m *DisableFeatureCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableFeatureCommand.Merge(m, src)
}
func (m *DisableFeatureCommand) XXX_Size() int {
	return xxx_messageInfo_DisableFeatureCommand.Size(m)
}
func (m *DisableFeatureCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableFeatureCommand.DiscardUnknown(m)
}

var xxx_messageInfo_DisableFeatureCommand proto.InternalMessageInfo

type AddVariationCommand struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddVariationCommand) Reset()         { *m = AddVariationCommand{} }
func (m *AddVariationCommand) String() string { return proto.CompactTextString(m) }
func (*AddVariationCommand) ProtoMessage()    {}
func (*AddVariationCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{11}
}

func (m *AddVariationCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddVariationCommand.Unmarshal(m, b)
}
func (m *AddVariationCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddVariationCommand.Marshal(b, m, deterministic)
}
func (m *AddVariationCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddVariationCommand.Merge(m, src)
}
func (m *AddVariationCommand) XXX_Size() int {
	return xxx_messageInfo_AddVariationCommand.Size(m)
}
func (m *AddVariationCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_AddVariationCommand.DiscardUnknown(m)
}

var xxx_messageInfo_AddVariationCommand proto.InternalMessageInfo

func (m *AddVariationCommand) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *AddVariationCommand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddVariationCommand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type RemoveVariationCommand struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveVariationCommand) Reset()         { *m = RemoveVariationCommand{} }
func (m *RemoveVariationCommand) String() string { return proto.CompactTextString(m) }
func (*RemoveVariationCommand) ProtoMessage()    {}
func (*RemoveVariationCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{12}
}

func (m *RemoveVariationCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveVariationCommand.Unmarshal(m, b)
}
func (m *RemoveVariationCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveVariationCommand.Marshal(b, m, deterministic)
}
func (m *RemoveVariationCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveVariationCommand.Merge(m, src)
}
func (m *RemoveVariationCommand) XXX_Size() int {
	return xxx_messageInfo_RemoveVariationCommand.Size(m)
}
func (m *RemoveVariationCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveVariationCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveVariationCommand proto.InternalMessageInfo

func (m *RemoveVariationCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ChangeVariationValueCommand struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeVariationValueCommand) Reset()         { *m = ChangeVariationValueCommand{} }
func (m *ChangeVariationValueCommand) String() string { return proto.CompactTextString(m) }
func (*ChangeVariationValueCommand) ProtoMessage()    {}
func (*ChangeVariationValueCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{13}
}

func (m *ChangeVariationValueCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeVariationValueCommand.Unmarshal(m, b)
}
func (m *ChangeVariationValueCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeVariationValueCommand.Marshal(b, m, deterministic)
}
func (m *ChangeVariationValueCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeVariationValueCommand.Merge(m, src)
}
func (m *ChangeVariationValueCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeVariationValueCommand.Size(m)
}
func (m *ChangeVariationValueCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeVariationValueCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeVariationValueCommand proto.InternalMessageInfo

func (m *ChangeVariationValueCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeVariationValueCommand) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ChangeVariationNameCommand struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeVariationNameCommand) Reset()         { *m = ChangeVariationNameCommand{} }
func (m *ChangeVariationNameCommand) String() string { return proto.CompactTextString(m) }
func (*ChangeVariationNameCommand) ProtoMessage()    {}
func (*ChangeVariationNameCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{14}
}

func (m *ChangeVariationNameCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeVariationNameCommand.Unmarshal(m, b)
}
func (m *ChangeVariationNameCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeVariationNameCommand.Marshal(b, m, deterministic)
}
func (m *ChangeVariationNameCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeVariationNameCommand.Merge(m, src)
}
func (m *ChangeVariationNameCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeVariationNameCommand.Size(m)
}
func (m *ChangeVariationNameCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeVariationNameCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeVariationNameCommand proto.InternalMessageInfo

func (m *ChangeVariationNameCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeVariationNameCommand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ChangeVariationDescriptionCommand struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeVariationDescriptionCommand) Reset()         { *m = ChangeVariationDescriptionCommand{} }
func (m *ChangeVariationDescriptionCommand) String() string { return proto.CompactTextString(m) }
func (*ChangeVariationDescriptionCommand) ProtoMessage()    {}
func (*ChangeVariationDescriptionCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{15}
}

func (m *ChangeVariationDescriptionCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeVariationDescriptionCommand.Unmarshal(m, b)
}
func (m *ChangeVariationDescriptionCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeVariationDescriptionCommand.Marshal(b, m, deterministic)
}
func (m *ChangeVariationDescriptionCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeVariationDescriptionCommand.Merge(m, src)
}
func (m *ChangeVariationDescriptionCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeVariationDescriptionCommand.Size(m)
}
func (m *ChangeVariationDescriptionCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeVariationDescriptionCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeVariationDescriptionCommand proto.InternalMessageInfo

func (m *ChangeVariationDescriptionCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeVariationDescriptionCommand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ChangeOffVariationCommand struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeOffVariationCommand) Reset()         { *m = ChangeOffVariationCommand{} }
func (m *ChangeOffVariationCommand) String() string { return proto.CompactTextString(m) }
func (*ChangeOffVariationCommand) ProtoMessage()    {}
func (*ChangeOffVariationCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{16}
}

func (m *ChangeOffVariationCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeOffVariationCommand.Unmarshal(m, b)
}
func (m *ChangeOffVariationCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeOffVariationCommand.Marshal(b, m, deterministic)
}
func (m *ChangeOffVariationCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeOffVariationCommand.Merge(m, src)
}
func (m *ChangeOffVariationCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeOffVariationCommand.Size(m)
}
func (m *ChangeOffVariationCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeOffVariationCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeOffVariationCommand proto.InternalMessageInfo

func (m *ChangeOffVariationCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AddUserToVariationCommand struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserToVariationCommand) Reset()         { *m = AddUserToVariationCommand{} }
func (m *AddUserToVariationCommand) String() string { return proto.CompactTextString(m) }
func (*AddUserToVariationCommand) ProtoMessage()    {}
func (*AddUserToVariationCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{17}
}

func (m *AddUserToVariationCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserToVariationCommand.Unmarshal(m, b)
}
func (m *AddUserToVariationCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserToVariationCommand.Marshal(b, m, deterministic)
}
func (m *AddUserToVariationCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserToVariationCommand.Merge(m, src)
}
func (m *AddUserToVariationCommand) XXX_Size() int {
	return xxx_messageInfo_AddUserToVariationCommand.Size(m)
}
func (m *AddUserToVariationCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserToVariationCommand.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserToVariationCommand proto.InternalMessageInfo

func (m *AddUserToVariationCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddUserToVariationCommand) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type RemoveUserFromVariationCommand struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveUserFromVariationCommand) Reset()         { *m = RemoveUserFromVariationCommand{} }
func (m *RemoveUserFromVariationCommand) String() string { return proto.CompactTextString(m) }
func (*RemoveUserFromVariationCommand) ProtoMessage()    {}
func (*RemoveUserFromVariationCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{18}
}

func (m *RemoveUserFromVariationCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserFromVariationCommand.Unmarshal(m, b)
}
func (m *RemoveUserFromVariationCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserFromVariationCommand.Marshal(b, m, deterministic)
}
func (m *RemoveUserFromVariationCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserFromVariationCommand.Merge(m, src)
}
func (m *RemoveUserFromVariationCommand) XXX_Size() int {
	return xxx_messageInfo_RemoveUserFromVariationCommand.Size(m)
}
func (m *RemoveUserFromVariationCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserFromVariationCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserFromVariationCommand proto.InternalMessageInfo

func (m *RemoveUserFromVariationCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RemoveUserFromVariationCommand) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type ChangeDefaultStrategyCommand struct {
	Strategy             *Strategy `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ChangeDefaultStrategyCommand) Reset()         { *m = ChangeDefaultStrategyCommand{} }
func (m *ChangeDefaultStrategyCommand) String() string { return proto.CompactTextString(m) }
func (*ChangeDefaultStrategyCommand) ProtoMessage()    {}
func (*ChangeDefaultStrategyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{19}
}

func (m *ChangeDefaultStrategyCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeDefaultStrategyCommand.Unmarshal(m, b)
}
func (m *ChangeDefaultStrategyCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeDefaultStrategyCommand.Marshal(b, m, deterministic)
}
func (m *ChangeDefaultStrategyCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeDefaultStrategyCommand.Merge(m, src)
}
func (m *ChangeDefaultStrategyCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeDefaultStrategyCommand.Size(m)
}
func (m *ChangeDefaultStrategyCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeDefaultStrategyCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeDefaultStrategyCommand proto.InternalMessageInfo

func (m *ChangeDefaultStrategyCommand) GetStrategy() *Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

type AddRuleCommand struct {
	Rule                 *Rule    `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRuleCommand) Reset()         { *m = AddRuleCommand{} }
func (m *AddRuleCommand) String() string { return proto.CompactTextString(m) }
func (*AddRuleCommand) ProtoMessage()    {}
func (*AddRuleCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{20}
}

func (m *AddRuleCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRuleCommand.Unmarshal(m, b)
}
func (m *AddRuleCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRuleCommand.Marshal(b, m, deterministic)
}
func (m *AddRuleCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRuleCommand.Merge(m, src)
}
func (m *AddRuleCommand) XXX_Size() int {
	return xxx_messageInfo_AddRuleCommand.Size(m)
}
func (m *AddRuleCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRuleCommand.DiscardUnknown(m)
}

var xxx_messageInfo_AddRuleCommand proto.InternalMessageInfo

func (m *AddRuleCommand) GetRule() *Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

type ChangeRuleStrategyCommand struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId               string    `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Strategy             *Strategy `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ChangeRuleStrategyCommand) Reset()         { *m = ChangeRuleStrategyCommand{} }
func (m *ChangeRuleStrategyCommand) String() string { return proto.CompactTextString(m) }
func (*ChangeRuleStrategyCommand) ProtoMessage()    {}
func (*ChangeRuleStrategyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{21}
}

func (m *ChangeRuleStrategyCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRuleStrategyCommand.Unmarshal(m, b)
}
func (m *ChangeRuleStrategyCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRuleStrategyCommand.Marshal(b, m, deterministic)
}
func (m *ChangeRuleStrategyCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRuleStrategyCommand.Merge(m, src)
}
func (m *ChangeRuleStrategyCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeRuleStrategyCommand.Size(m)
}
func (m *ChangeRuleStrategyCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRuleStrategyCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRuleStrategyCommand proto.InternalMessageInfo

func (m *ChangeRuleStrategyCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeRuleStrategyCommand) GetRuleId() string {
	if m != nil {
		return m.RuleId
	}
	return ""
}

func (m *ChangeRuleStrategyCommand) GetStrategy() *Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

type DeleteRuleCommand struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRuleCommand) Reset()         { *m = DeleteRuleCommand{} }
func (m *DeleteRuleCommand) String() string { return proto.CompactTextString(m) }
func (*DeleteRuleCommand) ProtoMessage()    {}
func (*DeleteRuleCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{22}
}

func (m *DeleteRuleCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRuleCommand.Unmarshal(m, b)
}
func (m *DeleteRuleCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRuleCommand.Marshal(b, m, deterministic)
}
func (m *DeleteRuleCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRuleCommand.Merge(m, src)
}
func (m *DeleteRuleCommand) XXX_Size() int {
	return xxx_messageInfo_DeleteRuleCommand.Size(m)
}
func (m *DeleteRuleCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRuleCommand.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRuleCommand proto.InternalMessageInfo

func (m *DeleteRuleCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AddClauseCommand struct {
	RuleId               string   `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Clause               *Clause  `protobuf:"bytes,2,opt,name=clause,proto3" json:"clause,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddClauseCommand) Reset()         { *m = AddClauseCommand{} }
func (m *AddClauseCommand) String() string { return proto.CompactTextString(m) }
func (*AddClauseCommand) ProtoMessage()    {}
func (*AddClauseCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{23}
}

func (m *AddClauseCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddClauseCommand.Unmarshal(m, b)
}
func (m *AddClauseCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddClauseCommand.Marshal(b, m, deterministic)
}
func (m *AddClauseCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddClauseCommand.Merge(m, src)
}
func (m *AddClauseCommand) XXX_Size() int {
	return xxx_messageInfo_AddClauseCommand.Size(m)
}
func (m *AddClauseCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_AddClauseCommand.DiscardUnknown(m)
}

var xxx_messageInfo_AddClauseCommand proto.InternalMessageInfo

func (m *AddClauseCommand) GetRuleId() string {
	if m != nil {
		return m.RuleId
	}
	return ""
}

func (m *AddClauseCommand) GetClause() *Clause {
	if m != nil {
		return m.Clause
	}
	return nil
}

type DeleteClauseCommand struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId               string   `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteClauseCommand) Reset()         { *m = DeleteClauseCommand{} }
func (m *DeleteClauseCommand) String() string { return proto.CompactTextString(m) }
func (*DeleteClauseCommand) ProtoMessage()    {}
func (*DeleteClauseCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{24}
}

func (m *DeleteClauseCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClauseCommand.Unmarshal(m, b)
}
func (m *DeleteClauseCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClauseCommand.Marshal(b, m, deterministic)
}
func (m *DeleteClauseCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClauseCommand.Merge(m, src)
}
func (m *DeleteClauseCommand) XXX_Size() int {
	return xxx_messageInfo_DeleteClauseCommand.Size(m)
}
func (m *DeleteClauseCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClauseCommand.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClauseCommand proto.InternalMessageInfo

func (m *DeleteClauseCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteClauseCommand) GetRuleId() string {
	if m != nil {
		return m.RuleId
	}
	return ""
}

type ChangeClauseAttributeCommand struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId               string   `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Attribute            string   `protobuf:"bytes,3,opt,name=attribute,proto3" json:"attribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeClauseAttributeCommand) Reset()         { *m = ChangeClauseAttributeCommand{} }
func (m *ChangeClauseAttributeCommand) String() string { return proto.CompactTextString(m) }
func (*ChangeClauseAttributeCommand) ProtoMessage()    {}
func (*ChangeClauseAttributeCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{25}
}

func (m *ChangeClauseAttributeCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeClauseAttributeCommand.Unmarshal(m, b)
}
func (m *ChangeClauseAttributeCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeClauseAttributeCommand.Marshal(b, m, deterministic)
}
func (m *ChangeClauseAttributeCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeClauseAttributeCommand.Merge(m, src)
}
func (m *ChangeClauseAttributeCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeClauseAttributeCommand.Size(m)
}
func (m *ChangeClauseAttributeCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeClauseAttributeCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeClauseAttributeCommand proto.InternalMessageInfo

func (m *ChangeClauseAttributeCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeClauseAttributeCommand) GetRuleId() string {
	if m != nil {
		return m.RuleId
	}
	return ""
}

func (m *ChangeClauseAttributeCommand) GetAttribute() string {
	if m != nil {
		return m.Attribute
	}
	return ""
}

type ChangeClauseOperatorCommand struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId               string          `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Operator             Clause_Operator `protobuf:"varint,3,opt,name=operator,proto3,enum=bucketeer.feature.Clause_Operator" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChangeClauseOperatorCommand) Reset()         { *m = ChangeClauseOperatorCommand{} }
func (m *ChangeClauseOperatorCommand) String() string { return proto.CompactTextString(m) }
func (*ChangeClauseOperatorCommand) ProtoMessage()    {}
func (*ChangeClauseOperatorCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{26}
}

func (m *ChangeClauseOperatorCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeClauseOperatorCommand.Unmarshal(m, b)
}
func (m *ChangeClauseOperatorCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeClauseOperatorCommand.Marshal(b, m, deterministic)
}
func (m *ChangeClauseOperatorCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeClauseOperatorCommand.Merge(m, src)
}
func (m *ChangeClauseOperatorCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeClauseOperatorCommand.Size(m)
}
func (m *ChangeClauseOperatorCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeClauseOperatorCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeClauseOperatorCommand proto.InternalMessageInfo

func (m *ChangeClauseOperatorCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeClauseOperatorCommand) GetRuleId() string {
	if m != nil {
		return m.RuleId
	}
	return ""
}

func (m *ChangeClauseOperatorCommand) GetOperator() Clause_Operator {
	if m != nil {
		return m.Operator
	}
	return Clause_EQUALS
}

type AddClauseValueCommand struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId               string   `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddClauseValueCommand) Reset()         { *m = AddClauseValueCommand{} }
func (m *AddClauseValueCommand) String() string { return proto.CompactTextString(m) }
func (*AddClauseValueCommand) ProtoMessage()    {}
func (*AddClauseValueCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{27}
}

func (m *AddClauseValueCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddClauseValueCommand.Unmarshal(m, b)
}
func (m *AddClauseValueCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddClauseValueCommand.Marshal(b, m, deterministic)
}
func (m *AddClauseValueCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddClauseValueCommand.Merge(m, src)
}
func (m *AddClauseValueCommand) XXX_Size() int {
	return xxx_messageInfo_AddClauseValueCommand.Size(m)
}
func (m *AddClauseValueCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_AddClauseValueCommand.DiscardUnknown(m)
}

var xxx_messageInfo_AddClauseValueCommand proto.InternalMessageInfo

func (m *AddClauseValueCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddClauseValueCommand) GetRuleId() string {
	if m != nil {
		return m.RuleId
	}
	return ""
}

func (m *AddClauseValueCommand) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RemoveClauseValueCommand struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId               string   `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveClauseValueCommand) Reset()         { *m = RemoveClauseValueCommand{} }
func (m *RemoveClauseValueCommand) String() string { return proto.CompactTextString(m) }
func (*RemoveClauseValueCommand) ProtoMessage()    {}
func (*RemoveClauseValueCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{28}
}

func (m *RemoveClauseValueCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveClauseValueCommand.Unmarshal(m, b)
}
func (m *RemoveClauseValueCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveClauseValueCommand.Marshal(b, m, deterministic)
}
func (m *RemoveClauseValueCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveClauseValueCommand.Merge(m, src)
}
func (m *RemoveClauseValueCommand) XXX_Size() int {
	return xxx_messageInfo_RemoveClauseValueCommand.Size(m)
}
func (m *RemoveClauseValueCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveClauseValueCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveClauseValueCommand proto.InternalMessageInfo

func (m *RemoveClauseValueCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RemoveClauseValueCommand) GetRuleId() string {
	if m != nil {
		return m.RuleId
	}
	return ""
}

func (m *RemoveClauseValueCommand) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ChangeFixedStrategyCommand struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId               string         `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Strategy             *FixedStrategy `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ChangeFixedStrategyCommand) Reset()         { *m = ChangeFixedStrategyCommand{} }
func (m *ChangeFixedStrategyCommand) String() string { return proto.CompactTextString(m) }
func (*ChangeFixedStrategyCommand) ProtoMessage()    {}
func (*ChangeFixedStrategyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{29}
}

func (m *ChangeFixedStrategyCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeFixedStrategyCommand.Unmarshal(m, b)
}
func (m *ChangeFixedStrategyCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeFixedStrategyCommand.Marshal(b, m, deterministic)
}
func (m *ChangeFixedStrategyCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeFixedStrategyCommand.Merge(m, src)
}
func (m *ChangeFixedStrategyCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeFixedStrategyCommand.Size(m)
}
func (m *ChangeFixedStrategyCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeFixedStrategyCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeFixedStrategyCommand proto.InternalMessageInfo

func (m *ChangeFixedStrategyCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeFixedStrategyCommand) GetRuleId() string {
	if m != nil {
		return m.RuleId
	}
	return ""
}

func (m *ChangeFixedStrategyCommand) GetStrategy() *FixedStrategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

type ChangeRolloutStrategyCommand struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId               string           `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Strategy             *RolloutStrategy `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ChangeRolloutStrategyCommand) Reset()         { *m = ChangeRolloutStrategyCommand{} }
func (m *ChangeRolloutStrategyCommand) String() string { return proto.CompactTextString(m) }
func (*ChangeRolloutStrategyCommand) ProtoMessage()    {}
func (*ChangeRolloutStrategyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{30}
}

func (m *ChangeRolloutStrategyCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRolloutStrategyCommand.Unmarshal(m, b)
}
func (m *ChangeRolloutStrategyCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRolloutStrategyCommand.Marshal(b, m, deterministic)
}
func (m *ChangeRolloutStrategyCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRolloutStrategyCommand.Merge(m, src)
}
func (m *ChangeRolloutStrategyCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeRolloutStrategyCommand.Size(m)
}
func (m *ChangeRolloutStrategyCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRolloutStrategyCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRolloutStrategyCommand proto.InternalMessageInfo

func (m *ChangeRolloutStrategyCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeRolloutStrategyCommand) GetRuleId() string {
	if m != nil {
		return m.RuleId
	}
	return ""
}

func (m *ChangeRolloutStrategyCommand) GetStrategy() *RolloutStrategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

type CreateSegmentCommand struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSegmentCommand) Reset()         { *m = CreateSegmentCommand{} }
func (m *CreateSegmentCommand) String() string { return proto.CompactTextString(m) }
func (*CreateSegmentCommand) ProtoMessage()    {}
func (*CreateSegmentCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{31}
}

func (m *CreateSegmentCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSegmentCommand.Unmarshal(m, b)
}
func (m *CreateSegmentCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSegmentCommand.Marshal(b, m, deterministic)
}
func (m *CreateSegmentCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSegmentCommand.Merge(m, src)
}
func (m *CreateSegmentCommand) XXX_Size() int {
	return xxx_messageInfo_CreateSegmentCommand.Size(m)
}
func (m *CreateSegmentCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSegmentCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSegmentCommand proto.InternalMessageInfo

func (m *CreateSegmentCommand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateSegmentCommand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type DeleteSegmentCommand struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSegmentCommand) Reset()         { *m = DeleteSegmentCommand{} }
func (m *DeleteSegmentCommand) String() string { return proto.CompactTextString(m) }
func (*DeleteSegmentCommand) ProtoMessage()    {}
func (*DeleteSegmentCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{32}
}

func (m *DeleteSegmentCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSegmentCommand.Unmarshal(m, b)
}
func (m *DeleteSegmentCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSegmentCommand.Marshal(b, m, deterministic)
}
func (m *DeleteSegmentCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSegmentCommand.Merge(m, src)
}
func (m *DeleteSegmentCommand) XXX_Size() int {
	return xxx_messageInfo_DeleteSegmentCommand.Size(m)
}
func (m *DeleteSegmentCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSegmentCommand.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSegmentCommand proto.InternalMessageInfo

type ChangeSegmentNameCommand struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeSegmentNameCommand) Reset()         { *m = ChangeSegmentNameCommand{} }
func (m *ChangeSegmentNameCommand) String() string { return proto.CompactTextString(m) }
func (*ChangeSegmentNameCommand) ProtoMessage()    {}
func (*ChangeSegmentNameCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{33}
}

func (m *ChangeSegmentNameCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeSegmentNameCommand.Unmarshal(m, b)
}
func (m *ChangeSegmentNameCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeSegmentNameCommand.Marshal(b, m, deterministic)
}
func (m *ChangeSegmentNameCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeSegmentNameCommand.Merge(m, src)
}
func (m *ChangeSegmentNameCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeSegmentNameCommand.Size(m)
}
func (m *ChangeSegmentNameCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeSegmentNameCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeSegmentNameCommand proto.InternalMessageInfo

func (m *ChangeSegmentNameCommand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ChangeSegmentDescriptionCommand struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeSegmentDescriptionCommand) Reset()         { *m = ChangeSegmentDescriptionCommand{} }
func (m *ChangeSegmentDescriptionCommand) String() string { return proto.CompactTextString(m) }
func (*ChangeSegmentDescriptionCommand) ProtoMessage()    {}
func (*ChangeSegmentDescriptionCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{34}
}

func (m *ChangeSegmentDescriptionCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeSegmentDescriptionCommand.Unmarshal(m, b)
}
func (m *ChangeSegmentDescriptionCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeSegmentDescriptionCommand.Marshal(b, m, deterministic)
}
func (m *ChangeSegmentDescriptionCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeSegmentDescriptionCommand.Merge(m, src)
}
func (m *ChangeSegmentDescriptionCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeSegmentDescriptionCommand.Size(m)
}
func (m *ChangeSegmentDescriptionCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeSegmentDescriptionCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeSegmentDescriptionCommand proto.InternalMessageInfo

func (m *ChangeSegmentDescriptionCommand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type AddSegmentUserCommand struct {
	UserIds              []string          `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	State                SegmentUser_State `protobuf:"varint,2,opt,name=state,proto3,enum=bucketeer.feature.SegmentUser_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AddSegmentUserCommand) Reset()         { *m = AddSegmentUserCommand{} }
func (m *AddSegmentUserCommand) String() string { return proto.CompactTextString(m) }
func (*AddSegmentUserCommand) ProtoMessage()    {}
func (*AddSegmentUserCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{35}
}

func (m *AddSegmentUserCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSegmentUserCommand.Unmarshal(m, b)
}
func (m *AddSegmentUserCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSegmentUserCommand.Marshal(b, m, deterministic)
}
func (m *AddSegmentUserCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSegmentUserCommand.Merge(m, src)
}
func (m *AddSegmentUserCommand) XXX_Size() int {
	return xxx_messageInfo_AddSegmentUserCommand.Size(m)
}
func (m *AddSegmentUserCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSegmentUserCommand.DiscardUnknown(m)
}

var xxx_messageInfo_AddSegmentUserCommand proto.InternalMessageInfo

func (m *AddSegmentUserCommand) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

func (m *AddSegmentUserCommand) GetState() SegmentUser_State {
	if m != nil {
		return m.State
	}
	return SegmentUser_INCLUDED
}

type DeleteSegmentUserCommand struct {
	UserIds              []string          `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	State                SegmentUser_State `protobuf:"varint,2,opt,name=state,proto3,enum=bucketeer.feature.SegmentUser_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeleteSegmentUserCommand) Reset()         { *m = DeleteSegmentUserCommand{} }
func (m *DeleteSegmentUserCommand) String() string { return proto.CompactTextString(m) }
func (*DeleteSegmentUserCommand) ProtoMessage()    {}
func (*DeleteSegmentUserCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{36}
}

func (m *DeleteSegmentUserCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSegmentUserCommand.Unmarshal(m, b)
}
func (m *DeleteSegmentUserCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSegmentUserCommand.Marshal(b, m, deterministic)
}
func (m *DeleteSegmentUserCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSegmentUserCommand.Merge(m, src)
}
func (m *DeleteSegmentUserCommand) XXX_Size() int {
	return xxx_messageInfo_DeleteSegmentUserCommand.Size(m)
}
func (m *DeleteSegmentUserCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSegmentUserCommand.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSegmentUserCommand proto.InternalMessageInfo

func (m *DeleteSegmentUserCommand) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

func (m *DeleteSegmentUserCommand) GetState() SegmentUser_State {
	if m != nil {
		return m.State
	}
	return SegmentUser_INCLUDED
}

type BulkUploadSegmentUsersCommand struct {
	Data                 []byte            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	State                SegmentUser_State `protobuf:"varint,2,opt,name=state,proto3,enum=bucketeer.feature.SegmentUser_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BulkUploadSegmentUsersCommand) Reset()         { *m = BulkUploadSegmentUsersCommand{} }
func (m *BulkUploadSegmentUsersCommand) String() string { return proto.CompactTextString(m) }
func (*BulkUploadSegmentUsersCommand) ProtoMessage()    {}
func (*BulkUploadSegmentUsersCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{37}
}

func (m *BulkUploadSegmentUsersCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkUploadSegmentUsersCommand.Unmarshal(m, b)
}
func (m *BulkUploadSegmentUsersCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkUploadSegmentUsersCommand.Marshal(b, m, deterministic)
}
func (m *BulkUploadSegmentUsersCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkUploadSegmentUsersCommand.Merge(m, src)
}
func (m *BulkUploadSegmentUsersCommand) XXX_Size() int {
	return xxx_messageInfo_BulkUploadSegmentUsersCommand.Size(m)
}
func (m *BulkUploadSegmentUsersCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkUploadSegmentUsersCommand.DiscardUnknown(m)
}

var xxx_messageInfo_BulkUploadSegmentUsersCommand proto.InternalMessageInfo

func (m *BulkUploadSegmentUsersCommand) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BulkUploadSegmentUsersCommand) GetState() SegmentUser_State {
	if m != nil {
		return m.State
	}
	return SegmentUser_INCLUDED
}

type IncrementFeatureVersionCommand struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrementFeatureVersionCommand) Reset()         { *m = IncrementFeatureVersionCommand{} }
func (m *IncrementFeatureVersionCommand) String() string { return proto.CompactTextString(m) }
func (*IncrementFeatureVersionCommand) ProtoMessage()    {}
func (*IncrementFeatureVersionCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{38}
}

func (m *IncrementFeatureVersionCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrementFeatureVersionCommand.Unmarshal(m, b)
}
func (m *IncrementFeatureVersionCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrementFeatureVersionCommand.Marshal(b, m, deterministic)
}
func (m *IncrementFeatureVersionCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrementFeatureVersionCommand.Merge(m, src)
}
func (m *IncrementFeatureVersionCommand) XXX_Size() int {
	return xxx_messageInfo_IncrementFeatureVersionCommand.Size(m)
}
func (m *IncrementFeatureVersionCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrementFeatureVersionCommand.DiscardUnknown(m)
}

var xxx_messageInfo_IncrementFeatureVersionCommand proto.InternalMessageInfo

type CloneFeatureCommand struct {
	EnvironmentNamespace string   `protobuf:"bytes,1,opt,name=environment_namespace,json=environmentNamespace,proto3" json:"environment_namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloneFeatureCommand) Reset()         { *m = CloneFeatureCommand{} }
func (m *CloneFeatureCommand) String() string { return proto.CompactTextString(m) }
func (*CloneFeatureCommand) ProtoMessage()    {}
func (*CloneFeatureCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{39}
}

func (m *CloneFeatureCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneFeatureCommand.Unmarshal(m, b)
}
func (m *CloneFeatureCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneFeatureCommand.Marshal(b, m, deterministic)
}
func (m *CloneFeatureCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneFeatureCommand.Merge(m, src)
}
func (m *CloneFeatureCommand) XXX_Size() int {
	return xxx_messageInfo_CloneFeatureCommand.Size(m)
}
func (m *CloneFeatureCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneFeatureCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CloneFeatureCommand proto.InternalMessageInfo

func (m *CloneFeatureCommand) GetEnvironmentNamespace() string {
	if m != nil {
		return m.EnvironmentNamespace
	}
	return ""
}

type ResetSamplingSeedCommand struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetSamplingSeedCommand) Reset()         { *m = ResetSamplingSeedCommand{} }
func (m *ResetSamplingSeedCommand) String() string { return proto.CompactTextString(m) }
func (*ResetSamplingSeedCommand) ProtoMessage()    {}
func (*ResetSamplingSeedCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f84e00dfd082627, []int{40}
}

func (m *ResetSamplingSeedCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetSamplingSeedCommand.Unmarshal(m, b)
}
func (m *ResetSamplingSeedCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetSamplingSeedCommand.Marshal(b, m, deterministic)
}
func (m *ResetSamplingSeedCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetSamplingSeedCommand.Merge(m, src)
}
func (m *ResetSamplingSeedCommand) XXX_Size() int {
	return xxx_messageInfo_ResetSamplingSeedCommand.Size(m)
}
func (m *ResetSamplingSeedCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetSamplingSeedCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ResetSamplingSeedCommand proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Command)(nil), "bucketeer.feature.Command")
	proto.RegisterType((*CreateFeatureCommand)(nil), "bucketeer.feature.CreateFeatureCommand")
	proto.RegisterType((*ArchiveFeatureCommand)(nil), "bucketeer.feature.ArchiveFeatureCommand")
	proto.RegisterType((*DeleteFeatureCommand)(nil), "bucketeer.feature.DeleteFeatureCommand")
	proto.RegisterType((*RenameFeatureCommand)(nil), "bucketeer.feature.RenameFeatureCommand")
	proto.RegisterType((*ChangeDescriptionCommand)(nil), "bucketeer.feature.ChangeDescriptionCommand")
	proto.RegisterType((*ChangeBulkUploadSegmentUsersStatusCommand)(nil), "bucketeer.feature.ChangeBulkUploadSegmentUsersStatusCommand")
	proto.RegisterType((*AddTagCommand)(nil), "bucketeer.feature.AddTagCommand")
	proto.RegisterType((*RemoveTagCommand)(nil), "bucketeer.feature.RemoveTagCommand")
	proto.RegisterType((*EnableFeatureCommand)(nil), "bucketeer.feature.EnableFeatureCommand")
	proto.RegisterType((*DisableFeatureCommand)(nil), "bucketeer.feature.DisableFeatureCommand")
	proto.RegisterType((*AddVariationCommand)(nil), "bucketeer.feature.AddVariationCommand")
	proto.RegisterType((*RemoveVariationCommand)(nil), "bucketeer.feature.RemoveVariationCommand")
	proto.RegisterType((*ChangeVariationValueCommand)(nil), "bucketeer.feature.ChangeVariationValueCommand")
	proto.RegisterType((*ChangeVariationNameCommand)(nil), "bucketeer.feature.ChangeVariationNameCommand")
	proto.RegisterType((*ChangeVariationDescriptionCommand)(nil), "bucketeer.feature.ChangeVariationDescriptionCommand")
	proto.RegisterType((*ChangeOffVariationCommand)(nil), "bucketeer.feature.ChangeOffVariationCommand")
	proto.RegisterType((*AddUserToVariationCommand)(nil), "bucketeer.feature.AddUserToVariationCommand")
	proto.RegisterType((*RemoveUserFromVariationCommand)(nil), "bucketeer.feature.RemoveUserFromVariationCommand")
	proto.RegisterType((*ChangeDefaultStrategyCommand)(nil), "bucketeer.feature.ChangeDefaultStrategyCommand")
	proto.RegisterType((*AddRuleCommand)(nil), "bucketeer.feature.AddRuleCommand")
	proto.RegisterType((*ChangeRuleStrategyCommand)(nil), "bucketeer.feature.ChangeRuleStrategyCommand")
	proto.RegisterType((*DeleteRuleCommand)(nil), "bucketeer.feature.DeleteRuleCommand")
	proto.RegisterType((*AddClauseCommand)(nil), "bucketeer.feature.AddClauseCommand")
	proto.RegisterType((*DeleteClauseCommand)(nil), "bucketeer.feature.DeleteClauseCommand")
	proto.RegisterType((*ChangeClauseAttributeCommand)(nil), "bucketeer.feature.ChangeClauseAttributeCommand")
	proto.RegisterType((*ChangeClauseOperatorCommand)(nil), "bucketeer.feature.ChangeClauseOperatorCommand")
	proto.RegisterType((*AddClauseValueCommand)(nil), "bucketeer.feature.AddClauseValueCommand")
	proto.RegisterType((*RemoveClauseValueCommand)(nil), "bucketeer.feature.RemoveClauseValueCommand")
	proto.RegisterType((*ChangeFixedStrategyCommand)(nil), "bucketeer.feature.ChangeFixedStrategyCommand")
	proto.RegisterType((*ChangeRolloutStrategyCommand)(nil), "bucketeer.feature.ChangeRolloutStrategyCommand")
	proto.RegisterType((*CreateSegmentCommand)(nil), "bucketeer.feature.CreateSegmentCommand")
	proto.RegisterType((*DeleteSegmentCommand)(nil), "bucketeer.feature.DeleteSegmentCommand")
	proto.RegisterType((*ChangeSegmentNameCommand)(nil), "bucketeer.feature.ChangeSegmentNameCommand")
	proto.RegisterType((*ChangeSegmentDescriptionCommand)(nil), "bucketeer.feature.ChangeSegmentDescriptionCommand")
	proto.RegisterType((*AddSegmentUserCommand)(nil), "bucketeer.feature.AddSegmentUserCommand")
	proto.RegisterType((*DeleteSegmentUserCommand)(nil), "bucketeer.feature.DeleteSegmentUserCommand")
	proto.RegisterType((*BulkUploadSegmentUsersCommand)(nil), "bucketeer.feature.BulkUploadSegmentUsersCommand")
	proto.RegisterType((*IncrementFeatureVersionCommand)(nil), "bucketeer.feature.IncrementFeatureVersionCommand")
	proto.RegisterType((*CloneFeatureCommand)(nil), "bucketeer.feature.CloneFeatureCommand")
	proto.RegisterType((*ResetSamplingSeedCommand)(nil), "bucketeer.feature.ResetSamplingSeedCommand")
}

func init() { proto.RegisterFile("proto/feature/command.proto", fileDescriptor_5f84e00dfd082627) }

var fileDescriptor_5f84e00dfd082627 = []byte{
	// 1121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x4b, 0x6f, 0xdb, 0xc6,
	0x13, 0x87, 0x2c, 0xbf, 0x32, 0xfe, 0x47, 0x70, 0x68, 0xd9, 0xa6, 0x65, 0xc7, 0x7f, 0x79, 0x9b,
	0x83, 0x9a, 0xa0, 0x14, 0x2a, 0x1f, 0x8a, 0x14, 0xae, 0x5b, 0x45, 0xae, 0x01, 0x17, 0x45, 0x0c,
	0xd0, 0x8f, 0xb6, 0x39, 0x54, 0x58, 0x69, 0x57, 0x32, 0x11, 0x8a, 0x64, 0xc9, 0xa5, 0x1a, 0x1f,
	0x7a, 0x2a, 0xd0, 0x7e, 0xa2, 0x02, 0xfd, 0x78, 0xc5, 0xbe, 0x68, 0x72, 0x45, 0x3b, 0xb1, 0x53,
	0xf4, 0x24, 0xee, 0xce, 0xcc, 0x6f, 0x1e, 0xbf, 0xdd, 0xd9, 0x11, 0x6c, 0x47, 0x71, 0xc8, 0xc2,
	0xf6, 0x88, 0x62, 0x96, 0xc6, 0xb4, 0x3d, 0x0c, 0x27, 0x13, 0x1c, 0x10, 0x47, 0xec, 0x5a, 0x4f,
	0x06, 0xe9, 0xf0, 0x2d, 0x65, 0x94, 0xc6, 0x8e, 0x52, 0x68, 0x6c, 0x8d, 0xc3, 0x70, 0xec, 0xd3,
	0xb6, 0x50, 0x18, 0xa4, 0xa3, 0x36, 0x0e, 0xae, 0xa5, 0x76, 0x63, 0xd7, 0x14, 0xfd, 0x1a, 0xe3,
	0x28, 0xa2, 0x71, 0xa2, 0xe4, 0x0d, 0xc3, 0x95, 0x8f, 0xd3, 0x84, 0x2a, 0x99, 0x11, 0x86, 0xfa,
	0x55, 0x42, 0xbb, 0x28, 0x8c, 0x53, 0x5f, 0x4b, 0x9e, 0x16, 0x25, 0x53, 0x1c, 0x7b, 0x98, 0x79,
	0x61, 0xa0, 0xc4, 0x3b, 0x45, 0x71, 0xc2, 0x62, 0xcc, 0xe8, 0xf8, 0xba, 0xdc, 0x67, 0x42, 0xc7,
	0x13, 0x1a, 0x30, 0x29, 0x44, 0x2f, 0x61, 0xa9, 0x27, 0x6b, 0x61, 0x39, 0xb0, 0xa4, 0xca, 0x62,
	0x57, 0x9a, 0x95, 0xd6, 0x4a, 0xa7, 0xee, 0xc8, 0x4c, 0x1d, 0x9d, 0xa9, 0xd3, 0x0d, 0xae, 0x5d,
	0xad, 0x84, 0xfe, 0xaa, 0x42, 0xbd, 0x17, 0x53, 0xcc, 0xe8, 0xb1, 0x84, 0xd6, 0x40, 0x35, 0x98,
	0xf3, 0x24, 0xc6, 0x23, 0x77, 0xce, 0x23, 0x96, 0x05, 0xf3, 0x01, 0x9e, 0x50, 0x7b, 0x4e, 0xec,
	0x88, 0x6f, 0xab, 0x09, 0x2b, 0x84, 0x26, 0xc3, 0xd8, 0x8b, 0x78, 0x1e, 0x76, 0x55, 0x88, 0xf2,
	0x5b, 0xd6, 0x01, 0x40, 0x96, 0x67, 0x62, 0xcf, 0x37, 0xab, 0xad, 0x95, 0xce, 0x8e, 0x33, 0xc3,
	0x94, 0x73, 0xa9, 0x95, 0xdc, 0x9c, 0x3e, 0xf7, 0xc9, 0xf0, 0x38, 0xb1, 0x17, 0x9a, 0x55, 0xee,
	0x93, 0x7f, 0x5b, 0x3f, 0x42, 0x83, 0xd0, 0x11, 0x4e, 0x7d, 0xd6, 0x0f, 0x83, 0x7e, 0xa6, 0xdc,
	0xf7, 0x02, 0x42, 0xdf, 0xd9, 0x8b, 0x22, 0xe7, 0xed, 0x99, 0x9c, 0x4f, 0x02, 0xb6, 0xdf, 0xb9,
	0xc4, 0x7e, 0x4a, 0xdd, 0x4d, 0x65, 0x7e, 0x1a, 0x64, 0x4e, 0x4f, 0xb8, 0xad, 0xf5, 0x06, 0xb6,
	0x33, 0xe4, 0xd1, 0x68, 0x06, 0x7a, 0xe9, 0xfd, 0xd0, 0xb6, 0x86, 0x1e, 0x8d, 0x0c, 0xec, 0x53,
	0xa8, 0xdd, 0xe0, 0xb1, 0xeb, 0x88, 0xda, 0xcb, 0xcd, 0x4a, 0xab, 0xd6, 0x69, 0x95, 0xd4, 0xe2,
	0xd8, 0xac, 0xc9, 0xf9, 0x75, 0x44, 0xdd, 0xc7, 0xd3, 0xfc, 0x12, 0x6d, 0xc2, 0x7a, 0x37, 0x1e,
	0x5e, 0x79, 0x53, 0x83, 0x37, 0xb4, 0x01, 0xf5, 0x23, 0xea, 0x53, 0x93, 0x4f, 0xf4, 0x1c, 0xea,
	0x2e, 0xe5, 0xac, 0x19, 0x3c, 0x6b, 0x5e, 0x2b, 0x37, 0xbc, 0xa2, 0x03, 0xb0, 0x7b, 0x57, 0x38,
	0x18, 0xd3, 0xa3, 0x1b, 0x2a, 0xb5, 0xbe, 0xc1, 0x79, 0x65, 0x86, 0x73, 0xf4, 0x77, 0x05, 0x3e,
	0x95, 0xe6, 0xaf, 0x52, 0xff, 0xed, 0x45, 0xe4, 0x87, 0x98, 0x9c, 0xc9, 0xf3, 0x7a, 0x91, 0xd0,
	0x38, 0x39, 0x63, 0x98, 0xa5, 0x89, 0xc6, 0x7b, 0x09, 0x8b, 0x89, 0xd8, 0x10, 0x50, 0xb5, 0xce,
	0x5e, 0x49, 0x45, 0x94, 0xb5, 0x23, 0x2d, 0x5d, 0x65, 0x60, 0x7d, 0x09, 0x0b, 0xfc, 0x4b, 0x9e,
	0xc9, 0x5a, 0xe7, 0xd9, 0xed, 0x96, 0xdc, 0xaf, 0xb0, 0xa6, 0xae, 0x34, 0xb1, 0xea, 0xb0, 0x30,
	0x0c, 0xd3, 0x80, 0x89, 0x43, 0x5b, 0x75, 0xe5, 0x02, 0xed, 0xc1, 0xe3, 0x2e, 0x21, 0xe7, 0x78,
	0xac, 0xa3, 0x5b, 0x85, 0x2a, 0xc3, 0x63, 0x95, 0x25, 0xff, 0x44, 0xcf, 0x60, 0xd5, 0xa5, 0x93,
	0x70, 0x4a, 0xef, 0xd4, 0xda, 0x80, 0xfa, 0xb7, 0x01, 0x1e, 0xf8, 0x26, 0x0b, 0x9b, 0xb0, 0x7e,
	0xe4, 0x25, 0x25, 0x02, 0x0c, 0x6b, 0x5d, 0x42, 0x32, 0xca, 0x35, 0x72, 0x1d, 0x16, 0xa6, 0xfc,
	0x68, 0x29, 0x6c, 0xb9, 0x78, 0xd8, 0x5d, 0x44, 0x2d, 0xd8, 0x90, 0x91, 0xcf, 0x78, 0x31, 0xee,
	0x3a, 0xea, 0xc1, 0xb6, 0x24, 0x30, 0xd3, 0x14, 0xe7, 0xfb, 0xb6, 0xd6, 0x90, 0x05, 0x39, 0x97,
	0x0b, 0x12, 0x7d, 0x03, 0x0d, 0x03, 0xe4, 0x35, 0x9e, 0xdc, 0xa7, 0xbd, 0xa0, 0x0b, 0xd8, 0x33,
	0x10, 0x4a, 0xce, 0xa3, 0x09, 0x64, 0xd4, 0x61, 0x6e, 0xb6, 0x0e, 0x2f, 0x60, 0x4b, 0xc2, 0xe6,
	0xaf, 0xe9, 0x6d, 0xa5, 0xf8, 0x1a, 0xb6, 0xba, 0x84, 0xf0, 0xf3, 0x73, 0x1e, 0xbe, 0x4f, 0x99,
	0x27, 0x91, 0x26, 0x34, 0xd6, 0x49, 0xf0, 0x6f, 0x74, 0x04, 0xbb, 0xb2, 0xea, 0x1c, 0xe3, 0x38,
	0x0e, 0x27, 0x0f, 0x42, 0xf9, 0x01, 0x76, 0xf4, 0x8d, 0x14, 0x1d, 0xe6, 0x4c, 0xbd, 0x0e, 0x1a,
	0xe3, 0x0b, 0x58, 0xd6, 0x0f, 0x86, 0xea, 0xfb, 0xdb, 0x65, 0xb7, 0x41, 0xa9, 0xb8, 0x99, 0x32,
	0xfa, 0x0a, 0x6a, 0x5d, 0x42, 0xdc, 0xd4, 0xcf, 0x98, 0x79, 0x01, 0xf3, 0xfc, 0xd1, 0x52, 0x30,
	0x9b, 0x25, 0x30, 0x5c, 0xdb, 0x15, 0x4a, 0xe8, 0x37, 0x5d, 0x4b, 0xbe, 0x67, 0x06, 0x65, 0x26,
	0xb6, 0x09, 0x4b, 0xdc, 0xa8, 0xef, 0x11, 0x95, 0xdb, 0x22, 0x5f, 0x9e, 0x14, 0xa3, 0xaf, 0xde,
	0x27, 0xfa, 0x4f, 0xe0, 0x89, 0x6c, 0x76, 0xf9, 0x04, 0x4c, 0x0a, 0x7f, 0x86, 0xd5, 0x2e, 0x21,
	0x3d, 0xf1, 0x82, 0x6b, 0x9d, 0x5c, 0x28, 0x95, 0x42, 0x28, 0x9f, 0xc3, 0xa2, 0x7c, 0xeb, 0x45,
	0x88, 0x2b, 0x9d, 0xad, 0x92, 0x40, 0x24, 0x94, 0xab, 0x14, 0xd1, 0x21, 0xac, 0xc9, 0x20, 0x8a,
	0x2e, 0x3e, 0x34, 0x7b, 0x44, 0x35, 0xb7, 0xd2, 0xbe, 0xcb, 0x58, 0xec, 0x0d, 0x52, 0x76, 0x6f,
	0x20, 0x6b, 0x07, 0x1e, 0x61, 0x6d, 0xac, 0x1a, 0xc0, 0xcd, 0x06, 0xfa, 0xa3, 0xa2, 0x6f, 0xb5,
	0xf4, 0x73, 0x1a, 0xd1, 0x18, 0xb3, 0x30, 0xbe, 0xb7, 0x9b, 0x43, 0x58, 0x0e, 0x95, 0xad, 0xf0,
	0x52, 0xeb, 0xa0, 0x5b, 0x8b, 0xe4, 0x68, 0x2f, 0x6e, 0x66, 0x83, 0x2e, 0x61, 0x3d, 0xe3, 0xe3,
	0xce, 0xbe, 0x72, 0x6b, 0x04, 0x59, 0xc3, 0xa9, 0xe6, 0x1b, 0xce, 0x4f, 0x60, 0xcb, 0x9b, 0xf6,
	0xef, 0x43, 0xff, 0x5e, 0xd1, 0xcd, 0xec, 0xd8, 0x7b, 0x47, 0xc9, 0x83, 0x0f, 0xfa, 0xc1, 0xcc,
	0x41, 0x6f, 0x96, 0x0d, 0x00, 0x79, 0x1f, 0xb9, 0xd3, 0xfe, 0x67, 0x45, 0x9f, 0x14, 0x37, 0xf4,
	0xfd, 0x30, 0x65, 0x0f, 0x8e, 0xe3, 0x70, 0x26, 0x8e, 0x32, 0x0a, 0x0d, 0x2f, 0xb9, 0x48, 0xbe,
	0xd7, 0x43, 0xa3, 0x7a, 0x5f, 0xef, 0x18, 0x26, 0x3e, 0xa0, 0x21, 0x67, 0x23, 0x4b, 0x11, 0x0d,
	0x39, 0x7a, 0x0c, 0x51, 0xfb, 0xf9, 0xf7, 0xa3, 0x6c, 0x6c, 0xe9, 0xc1, 0xff, 0x0b, 0xfa, 0x0f,
	0x9a, 0x5e, 0x02, 0x71, 0x3a, 0x73, 0x73, 0x83, 0x36, 0xdd, 0x82, 0x65, 0xde, 0x8a, 0xfb, 0x1e,
	0xe1, 0xa3, 0x0a, 0x1f, 0x48, 0x97, 0xf8, 0xfa, 0x84, 0x7c, 0xd4, 0x20, 0x82, 0x7e, 0x01, 0xbb,
	0x90, 0xfc, 0x7f, 0xe0, 0x32, 0x84, 0xa7, 0xe5, 0x93, 0x59, 0xae, 0xb8, 0x04, 0x33, 0x2c, 0xca,
	0xf3, 0x3f, 0x57, 0x7c, 0x7f, 0x94, 0xc3, 0x26, 0xec, 0x9e, 0x04, 0xc3, 0x98, 0x72, 0xa9, 0x9a,
	0x7b, 0x2e, 0x69, 0x9c, 0xdc, 0xf0, 0x82, 0xbe, 0x83, 0xb5, 0x9e, 0x1f, 0x06, 0xe6, 0x70, 0xba,
	0x0f, 0xeb, 0x34, 0x98, 0x7a, 0x71, 0x18, 0x70, 0xd3, 0x3e, 0x67, 0x39, 0x89, 0xf0, 0x50, 0xd3,
	0x5e, 0xcf, 0x09, 0x5f, 0x6b, 0x19, 0x6a, 0xf0, 0x3e, 0x90, 0x50, 0x76, 0x86, 0x27, 0x91, 0xef,
	0x05, 0xe3, 0x33, 0x4a, 0x89, 0x02, 0x7c, 0xf5, 0xfc, 0x4d, 0x6b, 0xec, 0xb1, 0xab, 0x74, 0xe0,
	0x0c, 0xc3, 0x49, 0x7b, 0x88, 0x3f, 0x23, 0x51, 0x3b, 0x4b, 0xa4, 0x5d, 0xf8, 0x8f, 0x35, 0x58,
	0x14, 0xcb, 0xfd, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x79, 0x33, 0x62, 0x74, 0x76, 0x0e, 0x00,
	0x00,
}
