// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/feature/feature_last_used_info.proto

package feature

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FeatureLastUsedInfo struct {
	FeatureId            string   `protobuf:"bytes,1,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	LastUsedAt           int64    `protobuf:"varint,3,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	CreatedAt            int64    `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClientOldestVersion  string   `protobuf:"bytes,5,opt,name=client_oldest_version,json=clientOldestVersion,proto3" json:"client_oldest_version,omitempty"`
	ClientLatestVersion  string   `protobuf:"bytes,6,opt,name=client_latest_version,json=clientLatestVersion,proto3" json:"client_latest_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureLastUsedInfo) Reset()         { *m = FeatureLastUsedInfo{} }
func (m *FeatureLastUsedInfo) String() string { return proto.CompactTextString(m) }
func (*FeatureLastUsedInfo) ProtoMessage()    {}
func (*FeatureLastUsedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_20c6318deac29365, []int{0}
}

func (m *FeatureLastUsedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureLastUsedInfo.Unmarshal(m, b)
}
func (m *FeatureLastUsedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureLastUsedInfo.Marshal(b, m, deterministic)
}
func (m *FeatureLastUsedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureLastUsedInfo.Merge(m, src)
}
func (m *FeatureLastUsedInfo) XXX_Size() int {
	return xxx_messageInfo_FeatureLastUsedInfo.Size(m)
}
func (m *FeatureLastUsedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureLastUsedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureLastUsedInfo proto.InternalMessageInfo

func (m *FeatureLastUsedInfo) GetFeatureId() string {
	if m != nil {
		return m.FeatureId
	}
	return ""
}

func (m *FeatureLastUsedInfo) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *FeatureLastUsedInfo) GetLastUsedAt() int64 {
	if m != nil {
		return m.LastUsedAt
	}
	return 0
}

func (m *FeatureLastUsedInfo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *FeatureLastUsedInfo) GetClientOldestVersion() string {
	if m != nil {
		return m.ClientOldestVersion
	}
	return ""
}

func (m *FeatureLastUsedInfo) GetClientLatestVersion() string {
	if m != nil {
		return m.ClientLatestVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*FeatureLastUsedInfo)(nil), "bucketeer.feature.FeatureLastUsedInfo")
}

func init() {
	proto.RegisterFile("proto/feature/feature_last_used_info.proto", fileDescriptor_20c6318deac29365)
}

var fileDescriptor_20c6318deac29365 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x89, 0xeb, 0xae, 0x74, 0xf0, 0x62, 0x16, 0xa1, 0x17, 0xa1, 0x78, 0x2a, 0x0b, 0xb6,
	0xa0, 0xbf, 0x60, 0x3d, 0x08, 0x0b, 0x0b, 0x42, 0x41, 0x0f, 0x5e, 0x42, 0x9a, 0x4c, 0x35, 0x18,
	0x9b, 0x25, 0x99, 0xfa, 0xd7, 0xbd, 0x8a, 0x69, 0xea, 0x76, 0x4f, 0xc9, 0xcc, 0x37, 0xef, 0xbd,
	0x61, 0x60, 0x73, 0xf0, 0x8e, 0x5c, 0xdd, 0xa1, 0xa4, 0xc1, 0xe3, 0xf4, 0x0a, 0x2b, 0x03, 0x89,
	0x21, 0xa0, 0x16, 0xa6, 0xef, 0x5c, 0x15, 0x87, 0xf8, 0x55, 0x3b, 0xa8, 0x4f, 0x24, 0x44, 0x5f,
	0xa5, 0xb9, 0xdb, 0x1f, 0x06, 0xeb, 0xa7, 0xf1, 0xbf, 0x97, 0x81, 0x5e, 0x02, 0xea, 0x5d, 0xdf,
	0x39, 0x7e, 0x03, 0x30, 0x59, 0x19, 0x9d, 0xb3, 0x82, 0x95, 0x59, 0x93, 0xa5, 0xce, 0x4e, 0xf3,
	0x1c, 0x2e, 0xbe, 0xd1, 0x07, 0xe3, 0xfa, 0xfc, 0xac, 0x60, 0xe5, 0xb2, 0x99, 0x4a, 0x5e, 0xc0,
	0xe5, 0x31, 0x5b, 0x52, 0xbe, 0x28, 0x58, 0xb9, 0x68, 0xc0, 0x26, 0xf3, 0x2d, 0xfd, 0x59, 0x2b,
	0x8f, 0x92, 0x46, 0x7e, 0x1e, 0x79, 0x96, 0x3a, 0x5b, 0xe2, 0xf7, 0x70, 0xad, 0xac, 0xc1, 0x9e,
	0x84, 0xb3, 0x1a, 0x03, 0x89, 0x29, 0x68, 0x19, 0x97, 0x58, 0x8f, 0xf0, 0x39, 0xb2, 0xd7, 0x14,
	0x7a, 0xd4, 0x58, 0x49, 0x73, 0xcd, 0x6a, 0xae, 0xd9, 0x47, 0x96, 0x34, 0x8f, 0x9b, 0xb7, 0xf2,
	0xdd, 0xd0, 0xc7, 0xd0, 0x56, 0xca, 0x7d, 0xd5, 0x4a, 0xde, 0xe9, 0x43, 0xfd, 0x7f, 0x9f, 0xfa,
	0xe4, 0xaa, 0xed, 0x2a, 0x96, 0x0f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x77, 0x06, 0xc4,
	0x6d, 0x01, 0x00, 0x00,
}
