// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/feature/target.proto

package feature

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Target struct {
	Variation            string   `protobuf:"bytes,1,opt,name=variation,proto3" json:"variation,omitempty"`
	Users                []string `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_576f39c1c0ebbd83, []int{0}
}

func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (m *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(m, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetVariation() string {
	if m != nil {
		return m.Variation
	}
	return ""
}

func (m *Target) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*Target)(nil), "bucketeer.feature.Target")
}

func init() { proto.RegisterFile("proto/feature/target.proto", fileDescriptor_576f39c1c0ebbd83) }

var fileDescriptor_576f39c1c0ebbd83 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4b, 0x4d, 0x2c, 0x29, 0x2d, 0x4a, 0xd5, 0x2f, 0x49, 0x2c, 0x4a, 0x4f, 0x2d,
	0xd1, 0x03, 0x0b, 0x0a, 0x09, 0x26, 0x95, 0x26, 0x67, 0xa7, 0x96, 0xa4, 0xa6, 0x16, 0xe9, 0x41,
	0xe5, 0x95, 0x6c, 0xb8, 0xd8, 0x42, 0xc0, 0x4a, 0x84, 0x64, 0xb8, 0x38, 0xcb, 0x12, 0x8b, 0x32,
	0x13, 0x4b, 0x32, 0xf3, 0xf3, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10, 0x02, 0x42, 0x22,
	0x5c, 0xac, 0xa5, 0xc5, 0xa9, 0x45, 0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0x9c, 0x41, 0x10, 0x8e,
	0x93, 0x56, 0x94, 0x46, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x72,
	0xa2, 0x6e, 0x4a, 0x81, 0x3e, 0xdc, 0x0e, 0x7d, 0x14, 0x97, 0x24, 0xb1, 0x81, 0xb9, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x68, 0x6e, 0x2f, 0x10, 0xa1, 0x00, 0x00, 0x00,
}
