// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/event/client/event.proto

package client

import (
	fmt "fmt"
	feature "github.com/ca-dp/bucketeer-go-server-sdk/proto/feature"
	user "github.com/ca-dp/bucketeer-go-server-sdk/proto/user"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	duration "github.com/golang/protobuf/ptypes/duration"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SourceId int32

const (
	SourceId_UNKNOWN    SourceId = 0
	SourceId_ANDROID    SourceId = 1
	SourceId_IOS        SourceId = 2
	SourceId_WEB        SourceId = 3
	SourceId_GOAL_BATCH SourceId = 4
	SourceId_GO_SERVER  SourceId = 5
)

var SourceId_name = map[int32]string{
	0: "UNKNOWN",
	1: "ANDROID",
	2: "IOS",
	3: "WEB",
	4: "GOAL_BATCH",
	5: "GO_SERVER",
}

var SourceId_value = map[string]int32{
	"UNKNOWN":    0,
	"ANDROID":    1,
	"IOS":        2,
	"WEB":        3,
	"GOAL_BATCH": 4,
	"GO_SERVER":  5,
}

func (x SourceId) String() string {
	return proto.EnumName(SourceId_name, int32(x))
}

func (SourceId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ead1ae0565f33ac0, []int{0}
}

type Event struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Event                *any.Any `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	EnvironmentNamespace string   `protobuf:"bytes,3,opt,name=environment_namespace,json=environmentNamespace,proto3" json:"environment_namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead1ae0565f33ac0, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetEvent() *any.Any {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Event) GetEnvironmentNamespace() string {
	if m != nil {
		return m.EnvironmentNamespace
	}
	return ""
}

type EvaluationEvent struct {
	Timestamp            int64           `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FeatureId            string          `protobuf:"bytes,2,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	FeatureVersion       int32           `protobuf:"varint,3,opt,name=feature_version,json=featureVersion,proto3" json:"feature_version,omitempty"`
	UserId               string          `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VariationId          string          `protobuf:"bytes,5,opt,name=variation_id,json=variationId,proto3" json:"variation_id,omitempty"`
	User                 *user.User      `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Reason               *feature.Reason `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	Tag                  string          `protobuf:"bytes,8,opt,name=tag,proto3" json:"tag,omitempty"`
	SourceId             SourceId        `protobuf:"varint,9,opt,name=source_id,json=sourceId,proto3,enum=bucketeer.event.client.SourceId" json:"source_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EvaluationEvent) Reset()         { *m = EvaluationEvent{} }
func (m *EvaluationEvent) String() string { return proto.CompactTextString(m) }
func (*EvaluationEvent) ProtoMessage()    {}
func (*EvaluationEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead1ae0565f33ac0, []int{1}
}

func (m *EvaluationEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvaluationEvent.Unmarshal(m, b)
}
func (m *EvaluationEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvaluationEvent.Marshal(b, m, deterministic)
}
func (m *EvaluationEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvaluationEvent.Merge(m, src)
}
func (m *EvaluationEvent) XXX_Size() int {
	return xxx_messageInfo_EvaluationEvent.Size(m)
}
func (m *EvaluationEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_EvaluationEvent.DiscardUnknown(m)
}

var xxx_messageInfo_EvaluationEvent proto.InternalMessageInfo

func (m *EvaluationEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *EvaluationEvent) GetFeatureId() string {
	if m != nil {
		return m.FeatureId
	}
	return ""
}

func (m *EvaluationEvent) GetFeatureVersion() int32 {
	if m != nil {
		return m.FeatureVersion
	}
	return 0
}

func (m *EvaluationEvent) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *EvaluationEvent) GetVariationId() string {
	if m != nil {
		return m.VariationId
	}
	return ""
}

func (m *EvaluationEvent) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *EvaluationEvent) GetReason() *feature.Reason {
	if m != nil {
		return m.Reason
	}
	return nil
}

func (m *EvaluationEvent) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *EvaluationEvent) GetSourceId() SourceId {
	if m != nil {
		return m.SourceId
	}
	return SourceId_UNKNOWN
}

type GoalEvent struct {
	Timestamp            int64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	GoalId               string                `protobuf:"bytes,2,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	UserId               string                `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Value                float64               `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	User                 *user.User            `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Evaluations          []*feature.Evaluation `protobuf:"bytes,6,rep,name=evaluations,proto3" json:"evaluations,omitempty"` // Deprecated: Do not use.
	Tag                  string                `protobuf:"bytes,7,opt,name=tag,proto3" json:"tag,omitempty"`
	SourceId             SourceId              `protobuf:"varint,8,opt,name=source_id,json=sourceId,proto3,enum=bucketeer.event.client.SourceId" json:"source_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GoalEvent) Reset()         { *m = GoalEvent{} }
func (m *GoalEvent) String() string { return proto.CompactTextString(m) }
func (*GoalEvent) ProtoMessage()    {}
func (*GoalEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead1ae0565f33ac0, []int{2}
}

func (m *GoalEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoalEvent.Unmarshal(m, b)
}
func (m *GoalEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoalEvent.Marshal(b, m, deterministic)
}
func (m *GoalEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoalEvent.Merge(m, src)
}
func (m *GoalEvent) XXX_Size() int {
	return xxx_messageInfo_GoalEvent.Size(m)
}
func (m *GoalEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GoalEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GoalEvent proto.InternalMessageInfo

func (m *GoalEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GoalEvent) GetGoalId() string {
	if m != nil {
		return m.GoalId
	}
	return ""
}

func (m *GoalEvent) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GoalEvent) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *GoalEvent) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

// Deprecated: Do not use.
func (m *GoalEvent) GetEvaluations() []*feature.Evaluation {
	if m != nil {
		return m.Evaluations
	}
	return nil
}

func (m *GoalEvent) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *GoalEvent) GetSourceId() SourceId {
	if m != nil {
		return m.SourceId
	}
	return SourceId_UNKNOWN
}

type MetricsEvent struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Event                *any.Any `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsEvent) Reset()         { *m = MetricsEvent{} }
func (m *MetricsEvent) String() string { return proto.CompactTextString(m) }
func (*MetricsEvent) ProtoMessage()    {}
func (*MetricsEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead1ae0565f33ac0, []int{3}
}

func (m *MetricsEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsEvent.Unmarshal(m, b)
}
func (m *MetricsEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsEvent.Marshal(b, m, deterministic)
}
func (m *MetricsEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsEvent.Merge(m, src)
}
func (m *MetricsEvent) XXX_Size() int {
	return xxx_messageInfo_MetricsEvent.Size(m)
}
func (m *MetricsEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsEvent proto.InternalMessageInfo

func (m *MetricsEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MetricsEvent) GetEvent() *any.Any {
	if m != nil {
		return m.Event
	}
	return nil
}

type GetEvaluationLatencyMetricsEvent struct {
	Labels               map[string]string  `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Duration             *duration.Duration `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetEvaluationLatencyMetricsEvent) Reset()         { *m = GetEvaluationLatencyMetricsEvent{} }
func (m *GetEvaluationLatencyMetricsEvent) String() string { return proto.CompactTextString(m) }
func (*GetEvaluationLatencyMetricsEvent) ProtoMessage()    {}
func (*GetEvaluationLatencyMetricsEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead1ae0565f33ac0, []int{4}
}

func (m *GetEvaluationLatencyMetricsEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEvaluationLatencyMetricsEvent.Unmarshal(m, b)
}
func (m *GetEvaluationLatencyMetricsEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEvaluationLatencyMetricsEvent.Marshal(b, m, deterministic)
}
func (m *GetEvaluationLatencyMetricsEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEvaluationLatencyMetricsEvent.Merge(m, src)
}
func (m *GetEvaluationLatencyMetricsEvent) XXX_Size() int {
	return xxx_messageInfo_GetEvaluationLatencyMetricsEvent.Size(m)
}
func (m *GetEvaluationLatencyMetricsEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEvaluationLatencyMetricsEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GetEvaluationLatencyMetricsEvent proto.InternalMessageInfo

func (m *GetEvaluationLatencyMetricsEvent) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *GetEvaluationLatencyMetricsEvent) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

type GetEvaluationSizeMetricsEvent struct {
	Labels               map[string]string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SizeByte             int32             `protobuf:"varint,2,opt,name=size_byte,json=sizeByte,proto3" json:"size_byte,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetEvaluationSizeMetricsEvent) Reset()         { *m = GetEvaluationSizeMetricsEvent{} }
func (m *GetEvaluationSizeMetricsEvent) String() string { return proto.CompactTextString(m) }
func (*GetEvaluationSizeMetricsEvent) ProtoMessage()    {}
func (*GetEvaluationSizeMetricsEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead1ae0565f33ac0, []int{5}
}

func (m *GetEvaluationSizeMetricsEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEvaluationSizeMetricsEvent.Unmarshal(m, b)
}
func (m *GetEvaluationSizeMetricsEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEvaluationSizeMetricsEvent.Marshal(b, m, deterministic)
}
func (m *GetEvaluationSizeMetricsEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEvaluationSizeMetricsEvent.Merge(m, src)
}
func (m *GetEvaluationSizeMetricsEvent) XXX_Size() int {
	return xxx_messageInfo_GetEvaluationSizeMetricsEvent.Size(m)
}
func (m *GetEvaluationSizeMetricsEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEvaluationSizeMetricsEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GetEvaluationSizeMetricsEvent proto.InternalMessageInfo

func (m *GetEvaluationSizeMetricsEvent) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *GetEvaluationSizeMetricsEvent) GetSizeByte() int32 {
	if m != nil {
		return m.SizeByte
	}
	return 0
}

type TimeoutErrorCountMetricsEvent struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeoutErrorCountMetricsEvent) Reset()         { *m = TimeoutErrorCountMetricsEvent{} }
func (m *TimeoutErrorCountMetricsEvent) String() string { return proto.CompactTextString(m) }
func (*TimeoutErrorCountMetricsEvent) ProtoMessage()    {}
func (*TimeoutErrorCountMetricsEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead1ae0565f33ac0, []int{6}
}

func (m *TimeoutErrorCountMetricsEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeoutErrorCountMetricsEvent.Unmarshal(m, b)
}
func (m *TimeoutErrorCountMetricsEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeoutErrorCountMetricsEvent.Marshal(b, m, deterministic)
}
func (m *TimeoutErrorCountMetricsEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeoutErrorCountMetricsEvent.Merge(m, src)
}
func (m *TimeoutErrorCountMetricsEvent) XXX_Size() int {
	return xxx_messageInfo_TimeoutErrorCountMetricsEvent.Size(m)
}
func (m *TimeoutErrorCountMetricsEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeoutErrorCountMetricsEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TimeoutErrorCountMetricsEvent proto.InternalMessageInfo

func (m *TimeoutErrorCountMetricsEvent) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type InternalErrorCountMetricsEvent struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalErrorCountMetricsEvent) Reset()         { *m = InternalErrorCountMetricsEvent{} }
func (m *InternalErrorCountMetricsEvent) String() string { return proto.CompactTextString(m) }
func (*InternalErrorCountMetricsEvent) ProtoMessage()    {}
func (*InternalErrorCountMetricsEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead1ae0565f33ac0, []int{7}
}

func (m *InternalErrorCountMetricsEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalErrorCountMetricsEvent.Unmarshal(m, b)
}
func (m *InternalErrorCountMetricsEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalErrorCountMetricsEvent.Marshal(b, m, deterministic)
}
func (m *InternalErrorCountMetricsEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalErrorCountMetricsEvent.Merge(m, src)
}
func (m *InternalErrorCountMetricsEvent) XXX_Size() int {
	return xxx_messageInfo_InternalErrorCountMetricsEvent.Size(m)
}
func (m *InternalErrorCountMetricsEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalErrorCountMetricsEvent.DiscardUnknown(m)
}

var xxx_messageInfo_InternalErrorCountMetricsEvent proto.InternalMessageInfo

func (m *InternalErrorCountMetricsEvent) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type OpsEvent struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FeatureId            string   `protobuf:"bytes,2,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	FeatureVersion       int32    `protobuf:"varint,3,opt,name=feature_version,json=featureVersion,proto3" json:"feature_version,omitempty"`
	VariationId          string   `protobuf:"bytes,4,opt,name=variation_id,json=variationId,proto3" json:"variation_id,omitempty"`
	GoalId               string   `protobuf:"bytes,5,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	UserId               string   `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpsEvent) Reset()         { *m = OpsEvent{} }
func (m *OpsEvent) String() string { return proto.CompactTextString(m) }
func (*OpsEvent) ProtoMessage()    {}
func (*OpsEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead1ae0565f33ac0, []int{8}
}

func (m *OpsEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpsEvent.Unmarshal(m, b)
}
func (m *OpsEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpsEvent.Marshal(b, m, deterministic)
}
func (m *OpsEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpsEvent.Merge(m, src)
}
func (m *OpsEvent) XXX_Size() int {
	return xxx_messageInfo_OpsEvent.Size(m)
}
func (m *OpsEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_OpsEvent.DiscardUnknown(m)
}

var xxx_messageInfo_OpsEvent proto.InternalMessageInfo

func (m *OpsEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *OpsEvent) GetFeatureId() string {
	if m != nil {
		return m.FeatureId
	}
	return ""
}

func (m *OpsEvent) GetFeatureVersion() int32 {
	if m != nil {
		return m.FeatureVersion
	}
	return 0
}

func (m *OpsEvent) GetVariationId() string {
	if m != nil {
		return m.VariationId
	}
	return ""
}

func (m *OpsEvent) GetGoalId() string {
	if m != nil {
		return m.GoalId
	}
	return ""
}

func (m *OpsEvent) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GoalBatchEvent struct {
	UserId                 string                   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserGoalEventsOverTags []*UserGoalEventsOverTag `protobuf:"bytes,2,rep,name=user_goal_events_over_tags,json=userGoalEventsOverTags,proto3" json:"user_goal_events_over_tags,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                 `json:"-"`
	XXX_unrecognized       []byte                   `json:"-"`
	XXX_sizecache          int32                    `json:"-"`
}

func (m *GoalBatchEvent) Reset()         { *m = GoalBatchEvent{} }
func (m *GoalBatchEvent) String() string { return proto.CompactTextString(m) }
func (*GoalBatchEvent) ProtoMessage()    {}
func (*GoalBatchEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead1ae0565f33ac0, []int{9}
}

func (m *GoalBatchEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoalBatchEvent.Unmarshal(m, b)
}
func (m *GoalBatchEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoalBatchEvent.Marshal(b, m, deterministic)
}
func (m *GoalBatchEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoalBatchEvent.Merge(m, src)
}
func (m *GoalBatchEvent) XXX_Size() int {
	return xxx_messageInfo_GoalBatchEvent.Size(m)
}
func (m *GoalBatchEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GoalBatchEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GoalBatchEvent proto.InternalMessageInfo

func (m *GoalBatchEvent) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GoalBatchEvent) GetUserGoalEventsOverTags() []*UserGoalEventsOverTag {
	if m != nil {
		return m.UserGoalEventsOverTags
	}
	return nil
}

type UserGoalEventsOverTag struct {
	Tag                  string           `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	UserGoalEvents       []*UserGoalEvent `protobuf:"bytes,2,rep,name=user_goal_events,json=userGoalEvents,proto3" json:"user_goal_events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserGoalEventsOverTag) Reset()         { *m = UserGoalEventsOverTag{} }
func (m *UserGoalEventsOverTag) String() string { return proto.CompactTextString(m) }
func (*UserGoalEventsOverTag) ProtoMessage()    {}
func (*UserGoalEventsOverTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead1ae0565f33ac0, []int{10}
}

func (m *UserGoalEventsOverTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGoalEventsOverTag.Unmarshal(m, b)
}
func (m *UserGoalEventsOverTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGoalEventsOverTag.Marshal(b, m, deterministic)
}
func (m *UserGoalEventsOverTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGoalEventsOverTag.Merge(m, src)
}
func (m *UserGoalEventsOverTag) XXX_Size() int {
	return xxx_messageInfo_UserGoalEventsOverTag.Size(m)
}
func (m *UserGoalEventsOverTag) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGoalEventsOverTag.DiscardUnknown(m)
}

var xxx_messageInfo_UserGoalEventsOverTag proto.InternalMessageInfo

func (m *UserGoalEventsOverTag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *UserGoalEventsOverTag) GetUserGoalEvents() []*UserGoalEvent {
	if m != nil {
		return m.UserGoalEvents
	}
	return nil
}

type UserGoalEvent struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	GoalId               string   `protobuf:"bytes,2,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	Value                float64  `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGoalEvent) Reset()         { *m = UserGoalEvent{} }
func (m *UserGoalEvent) String() string { return proto.CompactTextString(m) }
func (*UserGoalEvent) ProtoMessage()    {}
func (*UserGoalEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead1ae0565f33ac0, []int{11}
}

func (m *UserGoalEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGoalEvent.Unmarshal(m, b)
}
func (m *UserGoalEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGoalEvent.Marshal(b, m, deterministic)
}
func (m *UserGoalEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGoalEvent.Merge(m, src)
}
func (m *UserGoalEvent) XXX_Size() int {
	return xxx_messageInfo_UserGoalEvent.Size(m)
}
func (m *UserGoalEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGoalEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UserGoalEvent proto.InternalMessageInfo

func (m *UserGoalEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *UserGoalEvent) GetGoalId() string {
	if m != nil {
		return m.GoalId
	}
	return ""
}

func (m *UserGoalEvent) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterEnum("bucketeer.event.client.SourceId", SourceId_name, SourceId_value)
	proto.RegisterType((*Event)(nil), "bucketeer.event.client.Event")
	proto.RegisterType((*EvaluationEvent)(nil), "bucketeer.event.client.EvaluationEvent")
	proto.RegisterType((*GoalEvent)(nil), "bucketeer.event.client.GoalEvent")
	proto.RegisterType((*MetricsEvent)(nil), "bucketeer.event.client.MetricsEvent")
	proto.RegisterType((*GetEvaluationLatencyMetricsEvent)(nil), "bucketeer.event.client.GetEvaluationLatencyMetricsEvent")
	proto.RegisterMapType((map[string]string)(nil), "bucketeer.event.client.GetEvaluationLatencyMetricsEvent.LabelsEntry")
	proto.RegisterType((*GetEvaluationSizeMetricsEvent)(nil), "bucketeer.event.client.GetEvaluationSizeMetricsEvent")
	proto.RegisterMapType((map[string]string)(nil), "bucketeer.event.client.GetEvaluationSizeMetricsEvent.LabelsEntry")
	proto.RegisterType((*TimeoutErrorCountMetricsEvent)(nil), "bucketeer.event.client.TimeoutErrorCountMetricsEvent")
	proto.RegisterType((*InternalErrorCountMetricsEvent)(nil), "bucketeer.event.client.InternalErrorCountMetricsEvent")
	proto.RegisterType((*OpsEvent)(nil), "bucketeer.event.client.OpsEvent")
	proto.RegisterType((*GoalBatchEvent)(nil), "bucketeer.event.client.GoalBatchEvent")
	proto.RegisterType((*UserGoalEventsOverTag)(nil), "bucketeer.event.client.UserGoalEventsOverTag")
	proto.RegisterType((*UserGoalEvent)(nil), "bucketeer.event.client.UserGoalEvent")
}

func init() { proto.RegisterFile("proto/event/client/event.proto", fileDescriptor_ead1ae0565f33ac0) }

var fileDescriptor_ead1ae0565f33ac0 = []byte{
	// 878 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x61, 0x6e, 0xe2, 0x46,
	0x14, 0xae, 0x4d, 0x0c, 0xf8, 0xb1, 0xcb, 0xa2, 0x51, 0xb2, 0xeb, 0xd0, 0x26, 0xa2, 0x96, 0xaa,
	0xa2, 0x95, 0x62, 0x6b, 0xb3, 0xaa, 0xd4, 0x56, 0xea, 0x0f, 0x48, 0x50, 0x8a, 0x9a, 0x82, 0x34,
	0x49, 0x76, 0xdb, 0x6a, 0x25, 0x34, 0xd8, 0xb3, 0xac, 0xb5, 0x60, 0xa3, 0x99, 0x31, 0x2a, 0x39,
	0x47, 0x2f, 0xd2, 0x43, 0xf4, 0x02, 0xbd, 0x41, 0xaf, 0xd0, 0x13, 0x54, 0x33, 0x36, 0xc6, 0x26,
	0xa0, 0x65, 0x5b, 0xa9, 0x7f, 0x60, 0xe6, 0xbd, 0x6f, 0xde, 0x7c, 0xef, 0x9b, 0xc7, 0x27, 0xe0,
	0x74, 0xce, 0x22, 0x11, 0xb9, 0x74, 0x41, 0x43, 0xe1, 0x7a, 0xd3, 0x40, 0x7e, 0xa9, 0x8d, 0xa3,
	0x12, 0xe8, 0xe9, 0x38, 0xf6, 0xde, 0x53, 0x41, 0x29, 0x73, 0x92, 0x70, 0x82, 0x69, 0x1e, 0x4f,
	0xa2, 0x68, 0x32, 0xa5, 0xae, 0x42, 0x8d, 0xe3, 0xb7, 0x2e, 0x09, 0x97, 0xc9, 0x91, 0xe6, 0xe9,
	0x66, 0xca, 0x8f, 0x19, 0x11, 0x41, 0x14, 0xae, 0xf2, 0xc9, 0x95, 0x6f, 0x29, 0x11, 0x31, 0xa3,
	0x2e, 0x5d, 0x90, 0x69, 0x9c, 0xcf, 0x37, 0x8b, 0x79, 0x46, 0x09, 0xcf, 0x72, 0x47, 0x49, 0x2e,
	0xe6, 0x94, 0xa9, 0x8f, 0x24, 0x6c, 0xff, 0x0a, 0x46, 0x4f, 0xb2, 0x43, 0x75, 0xd0, 0x03, 0xdf,
	0xd2, 0x5a, 0x5a, 0xdb, 0xc4, 0x7a, 0xe0, 0xa3, 0xe7, 0x60, 0x28, 0xda, 0x96, 0xde, 0xd2, 0xda,
	0xb5, 0xf3, 0x43, 0x27, 0xe1, 0xe6, 0xac, 0xb8, 0x39, 0x9d, 0x70, 0x89, 0x13, 0x08, 0x7a, 0x09,
	0x47, 0x34, 0x5c, 0x04, 0x2c, 0x0a, 0x67, 0x34, 0x14, 0xa3, 0x90, 0xcc, 0x28, 0x9f, 0x13, 0x8f,
	0x5a, 0x25, 0x55, 0xee, 0x30, 0x97, 0x1c, 0xac, 0x72, 0xf6, 0x5f, 0x3a, 0x3c, 0xe9, 0x65, 0x1d,
	0x24, 0x24, 0x3e, 0x03, 0x53, 0x04, 0x33, 0xca, 0x05, 0x99, 0xcd, 0x15, 0x97, 0x12, 0x5e, 0x07,
	0xd0, 0x09, 0x40, 0xda, 0xda, 0x28, 0xf0, 0x15, 0x2f, 0x13, 0x9b, 0x69, 0xa4, 0xef, 0xa3, 0x2f,
	0xe1, 0xc9, 0x2a, 0xbd, 0xa0, 0x8c, 0x07, 0x51, 0xa8, 0xee, 0x37, 0x70, 0x3d, 0x0d, 0xbf, 0x4a,
	0xa2, 0xe8, 0x19, 0x54, 0xa4, 0x02, 0xb2, 0xc8, 0x81, 0x2a, 0x52, 0x96, 0xdb, 0xbe, 0x8f, 0x3e,
	0x87, 0x47, 0x0b, 0xc2, 0x02, 0x45, 0x48, 0x66, 0x0d, 0x95, 0xad, 0x65, 0xb1, 0xbe, 0x8f, 0xda,
	0x70, 0x20, 0xc1, 0x56, 0x39, 0x55, 0x65, 0xfd, 0xc8, 0x4a, 0xd4, 0x3b, 0x4e, 0x19, 0x56, 0x08,
	0xf4, 0x02, 0xca, 0xc9, 0x03, 0x58, 0x15, 0x85, 0x3d, 0xce, 0x61, 0x53, 0x42, 0x0e, 0x56, 0x00,
	0x9c, 0x02, 0x51, 0x03, 0x4a, 0x82, 0x4c, 0xac, 0xaa, 0xba, 0x56, 0x2e, 0xd1, 0x77, 0x60, 0xf2,
	0x28, 0x66, 0x9e, 0xea, 0xd8, 0x6c, 0x69, 0xed, 0xfa, 0x79, 0xcb, 0xd9, 0x3e, 0x58, 0xce, 0x8d,
	0x02, 0xf6, 0x7d, 0x5c, 0xe5, 0xe9, 0xca, 0xfe, 0x5d, 0x07, 0xf3, 0x2a, 0x22, 0xd3, 0x7d, 0xd4,
	0x7d, 0x06, 0x95, 0x49, 0x44, 0xa6, 0x6b, 0x69, 0xcb, 0x72, 0xdb, 0xf7, 0xf3, 0x72, 0x95, 0x0a,
	0x72, 0x1d, 0x82, 0x21, 0xdf, 0x8f, 0x2a, 0x15, 0x35, 0x9c, 0x6c, 0x32, 0x85, 0x8c, 0x0f, 0x2a,
	0x74, 0x01, 0xb5, 0xf5, 0x08, 0x73, 0xab, 0xdc, 0x2a, 0xb5, 0x6b, 0xe7, 0x27, 0x5b, 0x64, 0x5a,
	0x8f, 0x49, 0x57, 0xb7, 0x34, 0x9c, 0x3f, 0xb5, 0xd2, 0xac, 0xb2, 0x43, 0xb3, 0xea, 0x47, 0x6b,
	0xf6, 0x13, 0x3c, 0xfa, 0x91, 0x0a, 0x16, 0x78, 0x7c, 0x1f, 0xd5, 0x3e, 0xe2, 0x67, 0x62, 0xff,
	0xad, 0x41, 0xeb, 0x8a, 0x8a, 0x75, 0x37, 0xd7, 0x44, 0xd0, 0xd0, 0x5b, 0x16, 0xae, 0x7b, 0x03,
	0xe5, 0x29, 0x19, 0xd3, 0x29, 0xb7, 0x34, 0xa5, 0xc7, 0xe5, 0x2e, 0xea, 0x1f, 0xaa, 0xe4, 0x5c,
	0xab, 0x32, 0xbd, 0x50, 0xb0, 0x25, 0x4e, 0x6b, 0xa2, 0xaf, 0xa0, 0xba, 0xf2, 0x94, 0x94, 0xf1,
	0xf1, 0x03, 0xc6, 0x97, 0x29, 0x00, 0x67, 0xd0, 0xe6, 0x37, 0x50, 0xcb, 0x55, 0x93, 0x9a, 0xbf,
	0xa7, 0xcb, 0xd4, 0x2c, 0xe4, 0x72, 0x3d, 0x0a, 0xc9, 0xe8, 0x24, 0x9b, 0x6f, 0xf5, 0xaf, 0x35,
	0xfb, 0x4f, 0x0d, 0x4e, 0x0a, 0x54, 0x6f, 0x82, 0x7b, 0x5a, 0xe8, 0xf8, 0xe7, 0x8d, 0x8e, 0x3b,
	0x7b, 0x75, 0xbc, 0x59, 0x66, 0x6b, 0xbb, 0x9f, 0x82, 0xc9, 0x83, 0x7b, 0x3a, 0x1a, 0x2f, 0x45,
	0x42, 0xcd, 0xc0, 0x55, 0x19, 0xe8, 0x2e, 0x05, 0xfd, 0x2f, 0x4d, 0xbd, 0x80, 0x93, 0xdb, 0x60,
	0x46, 0xa3, 0x58, 0xf4, 0x18, 0x8b, 0xd8, 0x45, 0x14, 0x87, 0xa2, 0xd0, 0x53, 0x3a, 0x95, 0x5a,
	0x36, 0x95, 0xf6, 0x39, 0x9c, 0xf6, 0x43, 0x41, 0x59, 0x48, 0xa6, 0x7b, 0x9f, 0xf9, 0x43, 0x83,
	0xea, 0x70, 0xce, 0xff, 0x4f, 0x6f, 0xdc, 0xb4, 0xc0, 0x83, 0x87, 0x16, 0x98, 0x33, 0x0a, 0x63,
	0x97, 0x51, 0x94, 0xf3, 0x46, 0x61, 0xff, 0xa6, 0x41, 0x5d, 0xda, 0x50, 0x97, 0x08, 0xef, 0x5d,
	0xd2, 0x4d, 0x0e, 0xab, 0x15, 0x4c, 0x25, 0x80, 0xa6, 0x4a, 0xa8, 0x2b, 0xd4, 0xf3, 0xf3, 0x51,
	0xb4, 0xa0, 0x6c, 0x24, 0xc8, 0x84, 0x5b, 0xba, 0x9a, 0x90, 0xb3, 0x5d, 0x13, 0x22, 0xcd, 0x25,
	0xf3, 0x3b, 0x3e, 0x5c, 0x50, 0x76, 0x4b, 0x26, 0xf8, 0x69, 0xbc, 0x2d, 0xcc, 0xed, 0x7b, 0x38,
	0xda, 0x7a, 0xe0, 0xe1, 0x4b, 0xa0, 0x21, 0x34, 0x36, 0x59, 0xa5, 0x5c, 0xbe, 0xd8, 0x8b, 0x0b,
	0xae, 0x17, 0x39, 0xd8, 0x6f, 0xe0, 0x71, 0x01, 0xf0, 0x6f, 0xcd, 0x39, 0x9b, 0xd1, 0x52, 0xce,
	0x83, 0x9f, 0xdf, 0x41, 0x75, 0xe5, 0x6c, 0xa8, 0x06, 0x95, 0xbb, 0xc1, 0x0f, 0x83, 0xe1, 0xeb,
	0x41, 0xe3, 0x13, 0xb9, 0xe9, 0x0c, 0x2e, 0xf1, 0xb0, 0x7f, 0xd9, 0xd0, 0x50, 0x05, 0x4a, 0xfd,
	0xe1, 0x4d, 0x43, 0x97, 0x8b, 0xd7, 0xbd, 0x6e, 0xa3, 0x84, 0xea, 0x00, 0x57, 0xc3, 0xce, 0xf5,
	0xa8, 0xdb, 0xb9, 0xbd, 0xf8, 0xbe, 0x71, 0x80, 0x1e, 0x83, 0x79, 0x35, 0x1c, 0xdd, 0xf4, 0xf0,
	0xab, 0x1e, 0x6e, 0x18, 0x5d, 0xf7, 0x97, 0xb3, 0x49, 0x20, 0xde, 0xc5, 0x63, 0xc7, 0x8b, 0x66,
	0xae, 0x47, 0xce, 0xfc, 0xb9, 0x9b, 0x75, 0xef, 0x3e, 0xfc, 0x3f, 0x34, 0x2e, 0xab, 0xd8, 0xcb,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x5a, 0xce, 0x46, 0x2c, 0x09, 0x00, 0x00,
}
