// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/service.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListUsersRequest_OrderBy int32

const (
	ListUsersRequest_DEFAULT    ListUsersRequest_OrderBy = 0
	ListUsersRequest_CREATED_AT ListUsersRequest_OrderBy = 1
	ListUsersRequest_LAST_SEEN  ListUsersRequest_OrderBy = 2
)

var ListUsersRequest_OrderBy_name = map[int32]string{
	0: "DEFAULT",
	1: "CREATED_AT",
	2: "LAST_SEEN",
}

var ListUsersRequest_OrderBy_value = map[string]int32{
	"DEFAULT":    0,
	"CREATED_AT": 1,
	"LAST_SEEN":  2,
}

func (x ListUsersRequest_OrderBy) String() string {
	return proto.EnumName(ListUsersRequest_OrderBy_name, int32(x))
}

func (ListUsersRequest_OrderBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7741839c4b9012e0, []int{2, 0}
}

type ListUsersRequest_OrderDirection int32

const (
	ListUsersRequest_ASC  ListUsersRequest_OrderDirection = 0
	ListUsersRequest_DESC ListUsersRequest_OrderDirection = 1
)

var ListUsersRequest_OrderDirection_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}

var ListUsersRequest_OrderDirection_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x ListUsersRequest_OrderDirection) String() string {
	return proto.EnumName(ListUsersRequest_OrderDirection_name, int32(x))
}

func (ListUsersRequest_OrderDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7741839c4b9012e0, []int{2, 1}
}

type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EnvironmentNamespace string   `protobuf:"bytes,2,opt,name=environment_namespace,json=environmentNamespace,proto3" json:"environment_namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7741839c4b9012e0, []int{0}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetUserRequest) GetEnvironmentNamespace() string {
	if m != nil {
		return m.EnvironmentNamespace
	}
	return ""
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7741839c4b9012e0, []int{1}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ListUsersRequest struct {
	EnvironmentNamespace string                          `protobuf:"bytes,1,opt,name=environment_namespace,json=environmentNamespace,proto3" json:"environment_namespace,omitempty"`
	PageSize             int64                           `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor               string                          `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	OrderBy              ListUsersRequest_OrderBy        `protobuf:"varint,4,opt,name=order_by,json=orderBy,proto3,enum=bucketeer.user.ListUsersRequest_OrderBy" json:"order_by,omitempty"`
	OrderDirection       ListUsersRequest_OrderDirection `protobuf:"varint,5,opt,name=order_direction,json=orderDirection,proto3,enum=bucketeer.user.ListUsersRequest_OrderDirection" json:"order_direction,omitempty"`
	SearchKeyword        string                          `protobuf:"bytes,6,opt,name=search_keyword,json=searchKeyword,proto3" json:"search_keyword,omitempty"`
	From                 int64                           `protobuf:"varint,7,opt,name=from,proto3" json:"from,omitempty"`
	To                   int64                           `protobuf:"varint,8,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7741839c4b9012e0, []int{2}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetEnvironmentNamespace() string {
	if m != nil {
		return m.EnvironmentNamespace
	}
	return ""
}

func (m *ListUsersRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListUsersRequest) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *ListUsersRequest) GetOrderBy() ListUsersRequest_OrderBy {
	if m != nil {
		return m.OrderBy
	}
	return ListUsersRequest_DEFAULT
}

func (m *ListUsersRequest) GetOrderDirection() ListUsersRequest_OrderDirection {
	if m != nil {
		return m.OrderDirection
	}
	return ListUsersRequest_ASC
}

func (m *ListUsersRequest) GetSearchKeyword() string {
	if m != nil {
		return m.SearchKeyword
	}
	return ""
}

func (m *ListUsersRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *ListUsersRequest) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

type ListUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Cursor               string   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7741839c4b9012e0, []int{3}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ListUsersResponse) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func init() {
	proto.RegisterEnum("bucketeer.user.ListUsersRequest_OrderBy", ListUsersRequest_OrderBy_name, ListUsersRequest_OrderBy_value)
	proto.RegisterEnum("bucketeer.user.ListUsersRequest_OrderDirection", ListUsersRequest_OrderDirection_name, ListUsersRequest_OrderDirection_value)
	proto.RegisterType((*GetUserRequest)(nil), "bucketeer.user.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "bucketeer.user.GetUserResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "bucketeer.user.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "bucketeer.user.ListUsersResponse")
}

func init() { proto.RegisterFile("proto/user/service.proto", fileDescriptor_7741839c4b9012e0) }

var fileDescriptor_7741839c4b9012e0 = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x2f, 0x6d, 0xaf, 0x69, 0xa7, 0x5c, 0x2e, 0x0e, 0x77, 0xba, 0x54, 0xd0, 0x1a, 0x39,
	0x2c, 0x82, 0x09, 0xf4, 0xf0, 0xc9, 0xa7, 0x5e, 0x1b, 0x45, 0x2c, 0x27, 0x24, 0x3d, 0x14, 0x1f,
	0x0c, 0x6d, 0x32, 0xde, 0x85, 0xa3, 0xd9, 0xba, 0x9b, 0x9e, 0xf4, 0xbe, 0x94, 0xdf, 0xc1, 0x4f,
	0x26, 0xd9, 0x6d, 0x6b, 0x5a, 0xa8, 0xfa, 0x12, 0x76, 0x66, 0xfe, 0xf3, 0xe7, 0x37, 0xcc, 0x04,
	0xd8, 0x5c, 0xf0, 0x9c, 0x7b, 0x0b, 0x49, 0xc2, 0x93, 0x24, 0xee, 0xd2, 0x98, 0x5c, 0x95, 0x42,
	0x6b, 0xba, 0x88, 0x6f, 0x29, 0x27, 0x12, 0x6e, 0x51, 0x6d, 0x9f, 0x96, 0x94, 0xc5, 0x47, 0xcb,
	0x9c, 0xaf, 0x60, 0xbd, 0xa3, 0xfc, 0x4a, 0x92, 0x08, 0xe8, 0xfb, 0x82, 0x64, 0x8e, 0x8f, 0xc0,
	0x2c, 0xea, 0x51, 0x9a, 0x30, 0xa3, 0x63, 0x74, 0x9b, 0x41, 0xbd, 0x08, 0xdf, 0x27, 0x78, 0x0e,
	0xa7, 0x94, 0xdd, 0xa5, 0x82, 0x67, 0x33, 0xca, 0xf2, 0x28, 0x9b, 0xcc, 0x48, 0xce, 0x27, 0x31,
	0xb1, 0x8a, 0x92, 0x9d, 0x94, 0x8a, 0x97, 0xeb, 0x9a, 0xf3, 0x06, 0x8e, 0x37, 0xfe, 0x72, 0xce,
	0x33, 0x49, 0xd8, 0x85, 0x5a, 0xe1, 0xa8, 0xdc, 0x5b, 0xbd, 0x13, 0x77, 0x1b, 0xd4, 0x55, 0x5a,
	0xa5, 0x70, 0x7e, 0x55, 0xc1, 0x1e, 0xa5, 0x52, 0xb5, 0xcb, 0x35, 0xdf, 0x5e, 0x0c, 0x63, 0x3f,
	0x06, 0x3e, 0x86, 0xe6, 0x7c, 0x72, 0x4d, 0x91, 0x4c, 0xef, 0x35, 0x6f, 0x35, 0x68, 0x14, 0x89,
	0x30, 0xbd, 0x27, 0x7c, 0x08, 0xf5, 0x78, 0x21, 0x24, 0x17, 0xac, 0xaa, 0x07, 0xd6, 0x11, 0x0e,
	0xa0, 0xc1, 0x45, 0x42, 0x22, 0x9a, 0x2e, 0x59, 0xad, 0x63, 0x74, 0xad, 0x5e, 0x77, 0x17, 0x76,
	0x97, 0xce, 0xfd, 0x58, 0x34, 0x5c, 0x2c, 0x03, 0x93, 0xeb, 0x07, 0x7e, 0x86, 0x63, 0x6d, 0x92,
	0xa4, 0x82, 0xe2, 0x3c, 0xe5, 0x19, 0x3b, 0x54, 0x5e, 0xde, 0xff, 0x79, 0x0d, 0xd7, 0x6d, 0x81,
	0xc5, 0xb7, 0x62, 0x3c, 0x03, 0x4b, 0xd2, 0x44, 0xc4, 0x37, 0xd1, 0x2d, 0x2d, 0x7f, 0x70, 0x91,
	0xb0, 0xba, 0xc2, 0x3f, 0xd2, 0xd9, 0x0f, 0x3a, 0x89, 0x08, 0xb5, 0x6f, 0x82, 0xcf, 0x98, 0xa9,
	0xa6, 0x56, 0x6f, 0xb4, 0xa0, 0x92, 0x73, 0xd6, 0x50, 0x99, 0x4a, 0xce, 0x9d, 0xd7, 0x60, 0xae,
	0xc0, 0xb1, 0x05, 0xe6, 0xd0, 0x7f, 0xdb, 0xbf, 0x1a, 0x8d, 0xed, 0x03, 0xb4, 0x00, 0x06, 0x81,
	0xdf, 0x1f, 0xfb, 0xc3, 0xa8, 0x3f, 0xb6, 0x0d, 0x3c, 0x82, 0xe6, 0xa8, 0x1f, 0x8e, 0xa3, 0xd0,
	0xf7, 0x2f, 0xed, 0x8a, 0xf3, 0x1c, 0xac, 0x6d, 0x46, 0x34, 0xa1, 0xda, 0x0f, 0x07, 0xf6, 0x01,
	0x36, 0xa0, 0x36, 0xf4, 0xc3, 0x81, 0x6d, 0x38, 0x9f, 0xe0, 0x41, 0x69, 0xb2, 0xd5, 0x0d, 0xbc,
	0x84, 0xc3, 0x62, 0x66, 0xc9, 0x8c, 0x4e, 0x75, 0xef, 0x11, 0x68, 0x49, 0x69, 0x3d, 0x95, 0xf2,
	0x7a, 0x7a, 0x3f, 0x0d, 0x68, 0x15, 0xba, 0x50, 0xdf, 0x3d, 0x8e, 0xc0, 0x5c, 0x9d, 0x1a, 0x3e,
	0xd9, 0xf5, 0xdb, 0xbe, 0xf1, 0xf6, 0xd3, 0xbd, 0x75, 0xcd, 0xe7, 0x1c, 0x60, 0x00, 0xcd, 0x0d,
	0x36, 0x76, 0xfe, 0xb5, 0xab, 0xf6, 0xb3, 0xbf, 0x28, 0xd6, 0x9e, 0x17, 0x2f, 0xbe, 0x9c, 0x5d,
	0xa7, 0xf9, 0xcd, 0x62, 0xea, 0xc6, 0x7c, 0xe6, 0xc5, 0x93, 0x57, 0xc9, 0xdc, 0xdb, 0xb4, 0x79,
	0x7f, 0x7e, 0xd0, 0x69, 0x5d, 0xbd, 0xcf, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x97, 0xf0, 0x57,
	0x7b, 0xdf, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/bucketeer.user.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/bucketeer.user.UserService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) ListUsers(ctx context.Context, req *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bucketeer.user.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bucketeer.user.UserService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bucketeer.user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/service.proto",
}
