// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/service.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Deprecated: Do not use.
	EnvironmentNamespace string   `protobuf:"bytes,2,opt,name=environment_namespace,json=environmentNamespace,proto3" json:"environment_namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7741839c4b9012e0, []int{0}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetUserRequest) GetEnvironmentNamespace() string {
	if m != nil {
		return m.EnvironmentNamespace
	}
	return ""
}

type GetUserResponse struct {
	User                 *User       `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	UserEntity           *UserEntity `protobuf:"bytes,2,opt,name=user_entity,json=userEntity,proto3" json:"user_entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7741839c4b9012e0, []int{1}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetUserResponse) GetUserEntity() *UserEntity {
	if m != nil {
		return m.UserEntity
	}
	return nil
}

type ListUsersRequest struct {
	PageSize             int64    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor               string   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	EnvironmentNamespace string   `protobuf:"bytes,3,opt,name=environment_namespace,json=environmentNamespace,proto3" json:"environment_namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7741839c4b9012e0, []int{2}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListUsersRequest) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *ListUsersRequest) GetEnvironmentNamespace() string {
	if m != nil {
		return m.EnvironmentNamespace
	}
	return ""
}

type ListUsersResponse struct {
	Users                []*User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"` // Deprecated: Do not use.
	Cursor               string        `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	UserEntities         []*UserEntity `protobuf:"bytes,3,rep,name=user_entities,json=userEntities,proto3" json:"user_entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7741839c4b9012e0, []int{3}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ListUsersResponse) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *ListUsersResponse) GetUserEntities() []*UserEntity {
	if m != nil {
		return m.UserEntities
	}
	return nil
}

func init() {
	proto.RegisterType((*GetUserRequest)(nil), "bucketeer.user.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "bucketeer.user.GetUserResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "bucketeer.user.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "bucketeer.user.ListUsersResponse")
}

func init() { proto.RegisterFile("proto/user/service.proto", fileDescriptor_7741839c4b9012e0) }

var fileDescriptor_7741839c4b9012e0 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xfd, 0xa5, 0xf9, 0xd9, 0xda, 0x89, 0x56, 0x5d, 0x5a, 0x09, 0x11, 0xb4, 0x06, 0xc4, 0x5e,
	0x4c, 0xa0, 0x3d, 0x7a, 0x10, 0x0a, 0x22, 0x42, 0xf1, 0x90, 0xe2, 0xc5, 0x4b, 0x49, 0xd2, 0xa1,
	0x2e, 0xd2, 0x24, 0xee, 0x6e, 0x8a, 0x16, 0x3f, 0x8a, 0xdf, 0xc1, 0xaf, 0x28, 0xbb, 0x49, 0xd3,
	0x3f, 0x98, 0x5c, 0xc2, 0x66, 0xde, 0xdb, 0x79, 0xf3, 0xde, 0x0e, 0x98, 0x09, 0x8b, 0x45, 0xec,
	0xa6, 0x1c, 0x99, 0xcb, 0x91, 0x2d, 0x68, 0x88, 0x8e, 0x2a, 0x91, 0x56, 0x90, 0x86, 0x6f, 0x28,
	0x10, 0x99, 0x23, 0x51, 0xab, 0xb3, 0xc1, 0x94, 0x9f, 0x8c, 0x66, 0x07, 0xd0, 0x7a, 0x40, 0xf1,
	0xcc, 0x91, 0x79, 0xf8, 0x9e, 0x22, 0x17, 0xe4, 0x0c, 0x1a, 0x12, 0x9f, 0xd0, 0xa9, 0xa9, 0x75,
	0xb5, 0x5e, 0x73, 0x58, 0x33, 0x35, 0xaf, 0x2e, 0x4b, 0x8f, 0x53, 0x32, 0x80, 0x0e, 0x46, 0x0b,
	0xca, 0xe2, 0x68, 0x8e, 0x91, 0x98, 0x44, 0xfe, 0x1c, 0x79, 0xe2, 0x87, 0x68, 0xd6, 0x24, 0xd5,
	0x6b, 0x6f, 0x80, 0x4f, 0x2b, 0xcc, 0xfe, 0x80, 0xa3, 0x42, 0x83, 0x27, 0x71, 0xc4, 0x91, 0xf4,
	0xe0, 0xbf, 0xec, 0xa8, 0x14, 0x8c, 0x7e, 0xdb, 0xd9, 0x1e, 0xd6, 0x51, 0x5c, 0xc5, 0x20, 0xb7,
	0x60, 0xa8, 0x71, 0x30, 0x12, 0x54, 0x7c, 0x2a, 0x1d, 0xa3, 0x6f, 0xfd, 0x75, 0xe1, 0x5e, 0x31,
	0x3c, 0x48, 0x8b, 0xb3, 0xfd, 0x05, 0xc7, 0x23, 0xca, 0x95, 0x34, 0x5f, 0xfb, 0x6b, 0x26, 0xfe,
	0x0c, 0x27, 0x9c, 0x2e, 0x51, 0xe9, 0xeb, 0xde, 0xbe, 0x2c, 0x8c, 0xe9, 0x12, 0xc9, 0x29, 0xd4,
	0xc3, 0x94, 0xf1, 0x98, 0xe5, 0x86, 0xf2, 0xbf, 0x72, 0xdf, 0x7a, 0x85, 0xef, 0x6f, 0x0d, 0x4e,
	0x36, 0xe4, 0x73, 0xeb, 0x0e, 0xec, 0xc9, 0x09, 0xb9, 0xa9, 0x75, 0xf5, 0x32, 0xef, 0x2a, 0xf3,
	0x8c, 0x56, 0x3a, 0xd2, 0x1d, 0x1c, 0xae, 0x83, 0xa1, 0xc8, 0x4d, 0x5d, 0xf5, 0xab, 0x8a, 0xe6,
	0xa0, 0x88, 0x86, 0x22, 0xef, 0xff, 0x68, 0x60, 0x48, 0x70, 0x9c, 0xed, 0x0d, 0x19, 0x41, 0x23,
	0x7f, 0x26, 0x72, 0xbe, 0xdb, 0x64, 0x7b, 0x47, 0xac, 0x8b, 0x52, 0x3c, 0x33, 0x69, 0xff, 0x23,
	0x1e, 0x34, 0x0b, 0xef, 0xa4, 0xbb, 0xcb, 0xdf, 0x7d, 0x15, 0xeb, 0xb2, 0x82, 0xb1, 0xea, 0x39,
	0xbc, 0x7e, 0xb9, 0x9a, 0x51, 0xf1, 0x9a, 0x06, 0x4e, 0x18, 0xcf, 0xdd, 0xd0, 0xbf, 0x99, 0x26,
	0x6e, 0x71, 0xcd, 0x5d, 0x2f, 0x78, 0x50, 0x57, 0xe7, 0xc1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x57, 0x4a, 0xcc, 0x90, 0x1f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/bucketeer.user.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/bucketeer.user.UserService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) ListUsers(ctx context.Context, req *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bucketeer.user.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bucketeer.user.UserService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bucketeer.user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/service.proto",
}
