// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 map[string]string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	LastSeen             int64             `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

// Deprecated: Do not use.
func (m *User) GetLastSeen() int64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

type UserEntity struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []*Data       `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"` // Deprecated: Do not use.
	LastSeen             int64         `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	TaggedData           []*TaggedData `protobuf:"bytes,4,rep,name=tagged_data,json=taggedData,proto3" json:"tagged_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserEntity) Reset()         { *m = UserEntity{} }
func (m *UserEntity) String() string { return proto.CompactTextString(m) }
func (*UserEntity) ProtoMessage()    {}
func (*UserEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *UserEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEntity.Unmarshal(m, b)
}
func (m *UserEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEntity.Marshal(b, m, deterministic)
}
func (m *UserEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEntity.Merge(m, src)
}
func (m *UserEntity) XXX_Size() int {
	return xxx_messageInfo_UserEntity.Size(m)
}
func (m *UserEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEntity.DiscardUnknown(m)
}

var xxx_messageInfo_UserEntity proto.InternalMessageInfo

func (m *UserEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Deprecated: Do not use.
func (m *UserEntity) GetData() []*Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserEntity) GetLastSeen() int64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

func (m *UserEntity) GetTaggedData() []*TaggedData {
	if m != nil {
		return m.TaggedData
	}
	return nil
}

type Data struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Data) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TaggedData struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Data                 []*Data  `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaggedData) Reset()         { *m = TaggedData{} }
func (m *TaggedData) String() string { return proto.CompactTextString(m) }
func (*TaggedData) ProtoMessage()    {}
func (*TaggedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *TaggedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaggedData.Unmarshal(m, b)
}
func (m *TaggedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaggedData.Marshal(b, m, deterministic)
}
func (m *TaggedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaggedData.Merge(m, src)
}
func (m *TaggedData) XXX_Size() int {
	return xxx_messageInfo_TaggedData.Size(m)
}
func (m *TaggedData) XXX_DiscardUnknown() {
	xxx_messageInfo_TaggedData.DiscardUnknown(m)
}

var xxx_messageInfo_TaggedData proto.InternalMessageInfo

func (m *TaggedData) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *TaggedData) GetData() []*Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "bucketeer.user.User")
	proto.RegisterMapType((map[string]string)(nil), "bucketeer.user.User.DataEntry")
	proto.RegisterType((*UserEntity)(nil), "bucketeer.user.UserEntity")
	proto.RegisterType((*Data)(nil), "bucketeer.user.Data")
	proto.RegisterType((*TaggedData)(nil), "bucketeer.user.TaggedData")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0x4d, 0x14, 0x33, 0x85, 0x22, 0x4b, 0x85, 0x50, 0x41, 0x43, 0x40, 0xcc, 0x41,
	0x37, 0x50, 0x0f, 0x8a, 0xde, 0x8a, 0x05, 0xcf, 0x51, 0x2f, 0x5e, 0xca, 0x26, 0x19, 0x62, 0x68,
	0x4d, 0x4a, 0x32, 0x11, 0xf2, 0x7f, 0xfc, 0xa1, 0xb2, 0x1b, 0x4d, 0x68, 0x7b, 0xd0, 0x4b, 0x32,
	0x33, 0xcc, 0x7b, 0xf3, 0x3d, 0x58, 0x38, 0xd9, 0x54, 0x25, 0x95, 0x61, 0x53, 0x63, 0x65, 0x3e,
	0xd2, 0xf4, 0x62, 0x1c, 0x37, 0xc9, 0x0a, 0x09, 0xb1, 0x92, 0x7a, 0xea, 0x7f, 0x31, 0xb0, 0x5f,
	0x6b, 0xac, 0xc4, 0x18, 0x78, 0x9e, 0xba, 0xcc, 0x63, 0x81, 0x13, 0xf1, 0x3c, 0x15, 0x33, 0xb0,
	0x53, 0x45, 0xca, 0xe5, 0x9e, 0x15, 0x8c, 0x66, 0x67, 0x72, 0x5b, 0x27, 0xb5, 0x46, 0x3e, 0x2a,
	0x52, 0x8b, 0x82, 0xaa, 0x36, 0x32, 0xbb, 0xe2, 0x1c, 0x9c, 0xb5, 0xaa, 0x69, 0x59, 0x23, 0x16,
	0xae, 0xe5, 0xb1, 0xc0, 0x9a, 0x73, 0x97, 0x45, 0x47, 0x7a, 0xf8, 0x8c, 0x58, 0x4c, 0x6f, 0xc1,
	0xe9, 0x35, 0xe2, 0x18, 0xac, 0x15, 0xb6, 0x3f, 0x27, 0x75, 0x29, 0x26, 0x70, 0xf0, 0xa9, 0xd6,
	0x0d, 0xba, 0xdc, 0xcc, 0xba, 0xe6, 0x9e, 0xdf, 0x31, 0x8d, 0x09, 0xfa, 0xe4, 0xa2, 0xa0, 0x9c,
	0xda, 0x3d, 0xd8, 0xab, 0x2d, 0xd8, 0xc9, 0x2e, 0xac, 0xbe, 0x69, 0x48, 0x3a, 0xcc, 0xd3, 0x3d,
	0xcc, 0x01, 0x51, 0x3c, 0xc0, 0x88, 0x54, 0x96, 0x61, 0xba, 0x34, 0x8e, 0xb6, 0x71, 0x9c, 0xee,
	0x3a, 0xbe, 0x98, 0x15, 0xed, 0x1b, 0x01, 0xf5, 0xb5, 0x2f, 0xc1, 0xd6, 0xff, 0xff, 0x46, 0xf3,
	0x9f, 0x00, 0x06, 0x27, 0xad, 0x22, 0x95, 0xfd, 0xaa, 0x48, 0x65, 0x22, 0xf8, 0x3b, 0x57, 0x97,
	0x69, 0x7e, 0xf9, 0x76, 0x91, 0xe5, 0xf4, 0xde, 0xc4, 0x32, 0x29, 0x3f, 0xc2, 0x44, 0x5d, 0xa7,
	0x9b, 0xb0, 0xdf, 0x0e, 0x87, 0xb7, 0x10, 0x1f, 0x9a, 0xfa, 0xe6, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0x11, 0x3d, 0xed, 0x4f, 0x20, 0x02, 0x00, 0x00,
}
